import { colors } from './colors';

export const specforgeCodeTheme: Record<string, React.CSSProperties> = {
  'code[class*="language-"]': {
    color: colors.text.secondary,
    background: 'none',
    fontFamily: '"JetBrains Mono", monospace',
    fontSize: '0.95em',
    textAlign: 'left' as const,
    whiteSpace: 'pre' as const,
    wordSpacing: 'normal',
    wordBreak: 'normal' as const,
    wordWrap: 'normal' as const,
    lineHeight: '1.55',
    tabSize: 2,
    hyphens: 'none' as const,
  },
  'pre[class*="language-"]': {
    color: colors.text.secondary,
    background: '#0a0a12',
    fontFamily: '"JetBrains Mono", monospace',
    fontSize: '0.95em',
    textAlign: 'left' as const,
    whiteSpace: 'pre' as const,
    wordSpacing: 'normal',
    wordBreak: 'normal' as const,
    wordWrap: 'normal' as const,
    lineHeight: '1.55',
    tabSize: 2,
    hyphens: 'none' as const,
    padding: '1em',
    margin: '0',
    overflow: 'auto',
  },
  comment: { color: colors.text.muted },
  prolog: { color: colors.text.muted },
  doctype: { color: colors.text.muted },
  cdata: { color: colors.text.muted },
  punctuation: { color: colors.text.secondary },
  property: { color: colors.accent.teal },
  tag: { color: colors.accent.teal },
  boolean: { color: colors.accent.cyan },
  number: { color: colors.accent.cyan },
  constant: { color: colors.accent.cyan },
  symbol: { color: colors.accent.cyan },
  deleted: { color: colors.accent.red },
  selector: { color: colors.accent.green },
  'attr-name': { color: colors.accent.green },
  string: { color: colors.accent.green },
  char: { color: colors.accent.green },
  builtin: { color: colors.accent.green },
  inserted: { color: colors.accent.green },
  operator: { color: colors.text.secondary },
  entity: { color: colors.text.secondary, cursor: 'help' },
  url: { color: colors.text.secondary },
  '.language-css .token.string': { color: colors.text.secondary },
  '.style .token.string': { color: colors.text.secondary },
  atrule: { color: colors.accent.purple },
  'attr-value': { color: colors.accent.purple },
  keyword: { color: colors.accent.purple },
  function: { color: colors.accent.blue },
  'class-name': { color: colors.accent.yellow },
  regex: { color: colors.accent.orange },
  important: { color: colors.accent.orange, fontWeight: 'bold' },
  variable: { color: colors.accent.teal },
  bold: { fontWeight: 'bold' },
  italic: { fontStyle: 'italic' as const },
};
