use std::fmt::Write;

use super::{GroupBy, ModelIntermediate, ModelOptions, ModelFieldType};

pub fn render_dbml(model: &ModelIntermediate, options: &ModelOptions) -> String {
    let mut out = String::new();

    writeln!(out, "// Generated by specforge model").unwrap();
    writeln!(out, "// Model version: {}", model.model_version).unwrap();

    match options.group_by {
        GroupBy::Extension => render_grouped(model, &mut out),
        GroupBy::None => render_flat(model, &mut out),
    }

    // Named Ref declarations for edge types
    if !model.relationships.is_empty() {
        writeln!(out).unwrap();
        writeln!(out, "// ── Relationships ──").unwrap();
        writeln!(out).unwrap();
        for rel in &model.relationships {
            let source_col = rel.source_field.as_deref().unwrap_or("id");
            writeln!(out, "Ref {}: {}.{} > {}.id", rel.name, rel.source, source_col, rel.target).unwrap();
        }
    }

    out
}

fn render_grouped(model: &ModelIntermediate, out: &mut String) {
    for ext in &model.extensions {
        let entities: Vec<_> = model.entities.iter().filter(|e| e.extension == ext.name).collect();
        if entities.is_empty() {
            continue;
        }

        let short_name = ext.name.replace("@specforge/", "");
        writeln!(out).unwrap();
        writeln!(out, "// ── {} ──", ext.name).unwrap();
        writeln!(out).unwrap();

        // TableGroup
        writeln!(out, "TableGroup {} {{", short_name).unwrap();
        for entity in &entities {
            writeln!(out, "  {}", entity.name).unwrap();
        }
        writeln!(out, "}}").unwrap();

        // Enum definitions + Tables
        for entity in &entities {
            render_enums(entity, out);
            writeln!(out).unwrap();
            render_table(entity, out);
        }
    }
}

fn render_flat(model: &ModelIntermediate, out: &mut String) {
    for entity in &model.entities {
        render_enums(entity, out);
        writeln!(out).unwrap();
        render_table(entity, out);
    }
}

fn render_enums(entity: &super::ModelEntity, out: &mut String) {
    for field in &entity.fields {
        if field.field_type == ModelFieldType::Enum {
            if let Some(ref values) = field.enum_values {
                writeln!(out).unwrap();
                writeln!(out, "Enum {}_{} {{", entity.name, field.name).unwrap();
                for val in values {
                    writeln!(out, "  {}", val).unwrap();
                }
                writeln!(out, "}}").unwrap();
            }
        }
    }
}

fn render_table(entity: &super::ModelEntity, out: &mut String) {
    if entity.enhanced_by.is_empty() {
        writeln!(out, "Table {} {{", entity.name).unwrap();
    } else {
        writeln!(out, "Table {} {{ // enhanced by: {}", entity.name, entity.enhanced_by.join(", ")).unwrap();
    }

    for field in &entity.fields {
        let type_str = if field.field_type == ModelFieldType::Enum {
            format!("{}_{}", entity.name, field.name)
        } else {
            "string".to_string()
        };

        let mut attrs = Vec::new();

        if field.is_primary_key {
            attrs.push("pk".to_string());
        }
        if field.required && !field.is_primary_key {
            attrs.push("not null".to_string());
        }
        if let Some(ref target) = field.references {
            attrs.push(format!("ref: > {}.id", target));
        }

        // Build note from contribution, source, and description
        let mut note_parts: Vec<String> = Vec::new();
        if let Some(ref contrib) = field.contribution {
            note_parts.push(contrib.clone());
        }
        if let Some(ref source) = field.contributed_by {
            note_parts.push(format!("from {}", source));
        }
        if let Some(ref desc) = field.description {
            note_parts.push(desc.clone());
        }
        if !note_parts.is_empty() {
            attrs.push(format!("note: '{}'", note_parts.join(" | ")));
        }

        let attr_str = if attrs.is_empty() {
            String::new()
        } else {
            format!(" [{}]", attrs.join(", "))
        };

        writeln!(out, "  {} {}{}", field.name, type_str, attr_str).unwrap();
    }

    writeln!(out, "}}").unwrap();
}
