use std::collections::HashMap;
use std::fmt::Write;

use super::{Cardinality, GroupBy, ModelFieldType, ModelIntermediate, ModelOptions};

pub fn render_dbml(model: &ModelIntermediate, options: &ModelOptions) -> String {
    let mut out = String::new();

    writeln!(out, "// Generated by specforge model").unwrap();
    writeln!(out, "// Model version: {}", model.model_version).unwrap();

    let pk = primary_key_columns(model);

    match options.group_by {
        GroupBy::Extension => render_grouped(model, &pk, &mut out),
        GroupBy::None => render_flat(model, &pk, &mut out),
    }

    // Named Ref declarations for edge types. The operator encodes the
    // inferred cardinality (C13-10); the target column is the declared PK,
    // not a hardcoded `id`.
    if !model.relationships.is_empty() {
        writeln!(out).unwrap();
        writeln!(out, "// ── Relationships ──").unwrap();
        writeln!(out).unwrap();
        for rel in &model.relationships {
            let source_col = rel.source_field.as_deref().unwrap_or("id");
            let target_col = pk.get(rel.target.as_str()).copied().unwrap_or("id");
            writeln!(
                out,
                "Ref {}: {}.{} {} {}.{}",
                rel.name,
                rel.source,
                source_col,
                ref_operator(rel.cardinality),
                rel.target,
                target_col
            )
            .unwrap();
        }
    }

    out
}

fn render_grouped(model: &ModelIntermediate, pk: &HashMap<&str, &str>, out: &mut String) {
    for ext in &model.extensions {
        let entities: Vec<_> = model
            .entities
            .iter()
            .filter(|e| e.extension == ext.name)
            .collect();
        if entities.is_empty() {
            continue;
        }

        let short_name = ext.name.replace("@specforge/", "");
        writeln!(out).unwrap();
        writeln!(out, "// ── {} ──", ext.name).unwrap();
        writeln!(out).unwrap();

        // TableGroup
        writeln!(out, "TableGroup {} {{", short_name).unwrap();
        for entity in &entities {
            writeln!(out, "  {}", entity.name).unwrap();
        }
        writeln!(out, "}}").unwrap();

        // Enum definitions + Tables
        for entity in &entities {
            render_enums(entity, out);
            writeln!(out).unwrap();
            render_table(entity, pk, out);
        }
    }
}

fn render_flat(model: &ModelIntermediate, pk: &HashMap<&str, &str>, out: &mut String) {
    for entity in &model.entities {
        render_enums(entity, out);
        writeln!(out).unwrap();
        render_table(entity, pk, out);
    }
}

fn render_enums(entity: &super::ModelEntity, out: &mut String) {
    for field in &entity.fields {
        let has_enum_values =
            field.field_type == ModelFieldType::Enum && field.enum_values.is_some();
        if has_enum_values {
            writeln!(out).unwrap();
            writeln!(out, "Enum {}_{} {{", entity.name, field.name).unwrap();
            for val in field.enum_values.as_ref().unwrap() {
                writeln!(out, "  {}", val).unwrap();
            }
            writeln!(out, "}}").unwrap();
        }
    }
}

fn render_table(entity: &super::ModelEntity, pk: &HashMap<&str, &str>, out: &mut String) {
    if entity.enhanced_by.is_empty() {
        writeln!(out, "Table {} {{", entity.name).unwrap();
    } else {
        writeln!(
            out,
            "Table {} {{ // enhanced by: {}",
            entity.name,
            entity.enhanced_by.join(", ")
        )
        .unwrap();
    }

    for field in &entity.fields {
        let type_str = if field.field_type == ModelFieldType::Enum {
            format!("{}_{}", entity.name, field.name)
        } else {
            dbml_type(field.field_type).to_string()
        };

        let mut attrs = Vec::new();

        if field.is_primary_key {
            attrs.push("pk".to_string());
        }
        if field.required && !field.is_primary_key {
            attrs.push("not null".to_string());
        }
        if let Some(target) = &field.references {
            let target_col = pk.get(target.as_str()).copied().unwrap_or("id");
            attrs.push(format!("ref: > {target}.{target_col}"));
        }

        // Build note from contribution, source, and description
        let mut note_parts: Vec<String> = Vec::new();
        if let Some(ref contrib) = field.contribution {
            note_parts.push(contrib.clone());
        }
        if let Some(ref source) = field.contributed_by {
            note_parts.push(format!("from {}", source));
        }
        if let Some(ref desc) = field.description {
            note_parts.push(desc.clone());
        }
        if !note_parts.is_empty() {
            attrs.push(format!("note: '{}'", note_parts.join(" | ")));
        }

        let attr_str = if attrs.is_empty() {
            String::new()
        } else {
            format!(" [{}]", attrs.join(", "))
        };

        writeln!(out, "  {} {}{}", field.name, type_str, attr_str).unwrap();
    }

    writeln!(out, "}}").unwrap();
}

/// Real DBML column types instead of the previous all-`string` erasure (C13-10).
/// Lists have no native DBML column type and render as JSON-carrying `text`;
/// structured `block` fields render as `json`.
fn dbml_type(ft: ModelFieldType) -> &'static str {
    match ft {
        ModelFieldType::String | ModelFieldType::Reference => "varchar",
        ModelFieldType::Integer => "integer",
        ModelFieldType::Boolean => "boolean",
        ModelFieldType::StringList | ModelFieldType::ReferenceList => "text",
        ModelFieldType::Block => "json",
        // Enum fields render as the custom `Enum {entity}_{field}` type instead.
        ModelFieldType::Enum => "varchar",
    }
}

/// DBML Ref operator for a cardinality (dbdiagram.io semantics):
/// `-` one-to-one, `<` one-to-many, `>` many-to-one, `<>` many-to-many.
fn ref_operator(cardinality: Cardinality) -> &'static str {
    match cardinality {
        Cardinality::OneToOne => "-",
        Cardinality::OneToMany => "<",
        Cardinality::ManyToOne => ">",
        Cardinality::ManyToMany => "<>",
    }
}

/// Target-kind -> primary-key column name: the first `is_primary_key` field,
/// falling back to `id`.
fn primary_key_columns(model: &ModelIntermediate) -> HashMap<&str, &str> {
    model
        .entities
        .iter()
        .map(|e| {
            let col = e
                .fields
                .iter()
                .find(|f| f.is_primary_key)
                .map(|f| f.name.as_str())
                .unwrap_or("id");
            (e.name.as_str(), col)
        })
        .collect()
}
