//! @software — SDK-authored Wasm twin of the software builtin.
//!
//! The describe payloads are the protocol envelopes extracted from the
//! in-process builtin (regenerated by `xtask extract-extension-json`),
//! served through the SDK's `raw_category`; the handshake is derived by the
//! SDK from the extension metadata and contribution flags.

use specforge_extension_sdk::prelude::*;

static DESCRIBE_ENTITIES: &[u8] = include_bytes!("describe_entities.json");
static DESCRIBE_EDGES: &[u8] = include_bytes!("describe_edges.json");
static DESCRIBE_FIELDS: &[u8] = include_bytes!("describe_fields.json");
static DESCRIBE_SHARED_FIELDS: &[u8] = include_bytes!("describe_shared_fields.json");
static DESCRIBE_ENHANCEMENTS: &[u8] = include_bytes!("describe_enhancements.json");
static DESCRIBE_VALIDATION_RULES: &[u8] = include_bytes!("describe_validation_rules.json");
static DESCRIBE_SURFACES: &[u8] = include_bytes!("describe_surfaces.json");
static DESCRIBE_PASSES: &[u8] = include_bytes!("describe_passes.json");
static DESCRIBE_FEATURE_FLAGS: &[u8] = include_bytes!("describe_feature_flags.json");

#[specforge_extension_sdk::extension(name = "@specforge/software", version = "1.0.0")]
struct Software;

impl Contributions for Software {
    fn contribute(c: &mut ContributionsBuilder) {
        c.meta.peer_dependencies.push(PeerDependency {
            name: "@specforge/product".to_string(),
            version: "^1.0".to_string(),
            optional: false,
        });
        c.meta.sandbox_policy = Some(SandboxPolicy {
            max_memory_mb: Some(256),
            max_execution_ms: Some(5000),
            allowed_domains: vec![],
            allowed_paths: vec![],
            allowed_output_extensions: vec![],
            network_access: Some(false),
            file_system_access: Some(false),
        });

        for (category, bytes) in [
            ("entities", DESCRIBE_ENTITIES),
            ("edges", DESCRIBE_EDGES),
            ("fields", DESCRIBE_FIELDS),
            ("shared_fields", DESCRIBE_SHARED_FIELDS),
            ("enhancements", DESCRIBE_ENHANCEMENTS),
            ("validation_rules", DESCRIBE_VALIDATION_RULES),
            ("surfaces", DESCRIBE_SURFACES),
            ("passes", DESCRIBE_PASSES),
            ("feature_flags", DESCRIBE_FEATURE_FLAGS),
        ] {
            let envelope: serde_json::Value = serde_json::from_slice(bytes).unwrap_or_else(|e| {
                panic!("software describe '{category}' is not valid JSON: {e}")
            });
            c.raw_category(category, envelope["items"].clone());
        }
    }
}
