[package]
name = "xtask"
edition = "2024"
version = "0.1.0"
publish = false

[[bin]]
name = "build-builtins"
path = "src/build_builtins.rs"

[[bin]]
name = "snapshot-builtins"
path = "src/snapshot_builtins.rs"

[dependencies]
specforge-component = { path = "../crates/specforge-component" }
serde = "1.0"
specforge-emitter = { path = "../crates/specforge-emitter" }
specforge-installed = { path = "../crates/specforge-installed" }
specforge-wasm = { path = "../crates/specforge-wasm" }
specforge-protocol-types = { path = "../crates/specforge-protocol-types" }
serde_json = "1.0"
