//! Typed core diagnostic codes: [`Code`] (a fixed level) and
//! [`GradedCode`] (an `A###` finding whose pass sets the level). Only the
//! catalog table makes them (`codes::*`, generated by `catalog!`).

use crate::Level;

/// A core diagnostic code whose level is fixed: the host builds a
/// diagnostic from one (`specforge_common::Diagnostic::new`), so the
/// diagnostic's severity is this level. Only the catalog makes one
/// (`codes::*`); its `E`/`W`/`I` prefix agrees with its level or the crate
/// does not compile.
///
/// A catalog entry whose prefix contradicts its level is a compile error at
/// that entry (here a warning code catalogued as an error):
///
/// ```compile_fail,E0080
/// specforge_diagnostics::catalog! {
///     W112: Error core,
///         "Validation rule cannot fire",
///         "A rule that can never fire.";
/// }
/// ```
///
/// The same entry at its prefix's level compiles, and its constant carries
/// the level:
///
/// ```
/// specforge_diagnostics::catalog! {
///     W112: Warning core,
///         "Validation rule cannot fire",
///         "A rule that can never fire.";
/// }
/// assert_eq!(codes::W112.level(), specforge_diagnostics::Level::Warning);
/// assert_eq!(CATALOG[0].code, codes::W112.id());
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct Code {
    id: &'static str,
    level: Level,
}

impl Code {
    /// The constant for a catalogued core code; `catalog!` calls it in a
    /// `const` item, so a failed assertion is a compile error at that code.
    /// Host source never calls it (it would spell a code as text).
    #[doc(hidden)]
    pub const fn catalogued(id: &'static str, level: Level) -> Code {
        assert!(
            !matches!(level, Level::SetByPass),
            "a code whose pass sets its level is a GradedCode"
        );
        assert!(
            prefix_states(id, level),
            "an E/W/I prefix states the code's level"
        );
        Code { id, level }
    }

    /// The code as text (`W112`, `R-RES-005`).
    pub const fn id(self) -> &'static str {
        self.id
    }

    /// The catalogued level; never [`Level::SetByPass`].
    pub const fn level(self) -> Level {
        self.level
    }

    /// Whether a diagnostic's text code is this one (consumers compare with
    /// this).
    pub fn matches(self, code: &str) -> bool {
        self.id == code
    }
}

impl std::fmt::Display for Code {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.id)
    }
}

/// A core `A###` code: an analyze finding whose pass sets the severity per
/// finding (`specforge_common::Diagnostic::graded`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct GradedCode {
    id: &'static str,
}

impl GradedCode {
    /// The constant for a catalogued core `A###` code (see
    /// [`Code::catalogued`]).
    #[doc(hidden)]
    pub const fn catalogued(id: &'static str) -> GradedCode {
        assert!(
            prefix_states(id, Level::SetByPass),
            "only an A### code has its level set by its pass"
        );
        GradedCode { id }
    }

    /// The code as text (`A010`).
    pub const fn id(self) -> &'static str {
        self.id
    }

    /// Whether a diagnostic's text code is this one.
    pub fn matches(self, code: &str) -> bool {
        self.id == code
    }
}

impl std::fmt::Display for GradedCode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.id)
    }
}

/// Whether `code`'s prefix agrees with `level`: `E` error, `W` warning,
/// `I` info, `A` set by the analyze pass. The registry client's `R###` and
/// `R-<AREA>-###` state no level, so any fixed level agrees with them; any
/// other prefix agrees with none.
#[doc(hidden)]
pub const fn prefix_states(code: &str, level: Level) -> bool {
    let Some(prefix) = code.as_bytes().first() else {
        return false;
    };
    match (*prefix, level) {
        (b'E', Level::Error) | (b'W', Level::Warning) | (b'I', Level::Info) => true,
        (b'A', Level::SetByPass) => true,
        (b'R', level) => !matches!(level, Level::SetByPass),
        _ => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_prefix_states_its_level() {
        assert!(prefix_states("E001", Level::Error));
        assert!(prefix_states("W112", Level::Warning));
        assert!(prefix_states("I999", Level::Info));
        assert!(prefix_states("A010", Level::SetByPass));
        assert!(!prefix_states("W112", Level::Error));
        assert!(!prefix_states("E001", Level::Info));
        assert!(!prefix_states("A010", Level::Info));
        assert!(!prefix_states("I200", Level::SetByPass));
        assert!(!prefix_states("", Level::Error));
        assert!(!prefix_states("X509", Level::Error));
    }

    #[test]
    fn a_registry_client_code_takes_any_fixed_level() {
        for level in [Level::Error, Level::Warning, Level::Info] {
            assert!(prefix_states("R003", level));
            assert!(prefix_states("R-RES-005", level));
        }
        assert!(!prefix_states("R001", Level::SetByPass));
    }

    #[test]
    fn a_code_prints_and_matches_its_id() {
        let code = Code::catalogued("W112", Level::Warning);
        assert_eq!(code.to_string(), "W112");
        assert!(code.matches("W112"));
        assert!(!code.matches("W113"));
        let graded = GradedCode::catalogued("A010");
        assert_eq!(graded.to_string(), "A010");
        assert!(graded.matches("A010"));
    }
}
