/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 72
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 43
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 9
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_comment = 2,
  anon_sym_use = 3,
  sym_import_path = 4,
  anon_sym_LBRACE = 5,
  anon_sym_COMMA = 6,
  anon_sym_RBRACE = 7,
  anon_sym_spec = 8,
  anon_sym_ref = 9,
  sym_scheme_ref_id = 10,
  anon_sym_define = 11,
  anon_sym_verify = 12,
  anon_sym_LBRACK = 13,
  anon_sym_RBRACK = 14,
  sym_string = 15,
  sym_triple_quoted_string = 16,
  sym_date_literal = 17,
  sym_integer = 18,
  anon_sym_true = 19,
  anon_sym_false = 20,
  sym_source_file = 21,
  sym_use_import = 22,
  sym_selective_import = 23,
  sym__block = 24,
  sym_entity_block = 25,
  sym_spec_block = 26,
  sym_ref_block = 27,
  sym_ref_inline = 28,
  sym_ref_full = 29,
  sym_define_block = 30,
  sym_field = 31,
  sym__value = 32,
  sym_verify_statement = 33,
  sym_list = 34,
  sym__list_item = 35,
  sym_nested_block = 36,
  sym_boolean = 37,
  aux_sym_source_file_repeat1 = 38,
  aux_sym_selective_import_repeat1 = 39,
  aux_sym_entity_block_repeat1 = 40,
  aux_sym_ref_full_repeat1 = 41,
  aux_sym_list_repeat1 = 42,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [anon_sym_use] = "use",
  [sym_import_path] = "import_path",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_spec] = "spec",
  [anon_sym_ref] = "ref",
  [sym_scheme_ref_id] = "scheme_ref_id",
  [anon_sym_define] = "define",
  [anon_sym_verify] = "verify",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_string] = "string",
  [sym_triple_quoted_string] = "triple_quoted_string",
  [sym_date_literal] = "date_literal",
  [sym_integer] = "integer",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_source_file] = "source_file",
  [sym_use_import] = "use_import",
  [sym_selective_import] = "selective_import",
  [sym__block] = "_block",
  [sym_entity_block] = "entity_block",
  [sym_spec_block] = "spec_block",
  [sym_ref_block] = "ref_block",
  [sym_ref_inline] = "ref_inline",
  [sym_ref_full] = "ref_full",
  [sym_define_block] = "define_block",
  [sym_field] = "field",
  [sym__value] = "_value",
  [sym_verify_statement] = "verify_statement",
  [sym_list] = "list",
  [sym__list_item] = "_list_item",
  [sym_nested_block] = "nested_block",
  [sym_boolean] = "boolean",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_selective_import_repeat1] = "selective_import_repeat1",
  [aux_sym_entity_block_repeat1] = "entity_block_repeat1",
  [aux_sym_ref_full_repeat1] = "ref_full_repeat1",
  [aux_sym_list_repeat1] = "list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [anon_sym_use] = anon_sym_use,
  [sym_import_path] = sym_import_path,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_spec] = anon_sym_spec,
  [anon_sym_ref] = anon_sym_ref,
  [sym_scheme_ref_id] = sym_scheme_ref_id,
  [anon_sym_define] = anon_sym_define,
  [anon_sym_verify] = anon_sym_verify,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_string] = sym_string,
  [sym_triple_quoted_string] = sym_triple_quoted_string,
  [sym_date_literal] = sym_date_literal,
  [sym_integer] = sym_integer,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_source_file] = sym_source_file,
  [sym_use_import] = sym_use_import,
  [sym_selective_import] = sym_selective_import,
  [sym__block] = sym__block,
  [sym_entity_block] = sym_entity_block,
  [sym_spec_block] = sym_spec_block,
  [sym_ref_block] = sym_ref_block,
  [sym_ref_inline] = sym_ref_inline,
  [sym_ref_full] = sym_ref_full,
  [sym_define_block] = sym_define_block,
  [sym_field] = sym_field,
  [sym__value] = sym__value,
  [sym_verify_statement] = sym_verify_statement,
  [sym_list] = sym_list,
  [sym__list_item] = sym__list_item,
  [sym_nested_block] = sym_nested_block,
  [sym_boolean] = sym_boolean,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_selective_import_repeat1] = aux_sym_selective_import_repeat1,
  [aux_sym_entity_block_repeat1] = aux_sym_entity_block_repeat1,
  [aux_sym_ref_full_repeat1] = aux_sym_ref_full_repeat1,
  [aux_sym_list_repeat1] = aux_sym_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_use] = {
    .visible = true,
    .named = false,
  },
  [sym_import_path] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_spec] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ref] = {
    .visible = true,
    .named = false,
  },
  [sym_scheme_ref_id] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_define] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_verify] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_triple_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_date_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_use_import] = {
    .visible = true,
    .named = true,
  },
  [sym_selective_import] = {
    .visible = true,
    .named = true,
  },
  [sym__block] = {
    .visible = false,
    .named = true,
  },
  [sym_entity_block] = {
    .visible = true,
    .named = true,
  },
  [sym_spec_block] = {
    .visible = true,
    .named = true,
  },
  [sym_ref_block] = {
    .visible = true,
    .named = true,
  },
  [sym_ref_inline] = {
    .visible = true,
    .named = true,
  },
  [sym_ref_full] = {
    .visible = true,
    .named = true,
  },
  [sym_define_block] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_verify_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym__list_item] = {
    .visible = false,
    .named = true,
  },
  [sym_nested_block] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_selective_import_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_entity_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_ref_full_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_description = 1,
  field_id = 2,
  field_key = 3,
  field_kind = 4,
  field_name = 5,
  field_path = 6,
  field_selective = 7,
  field_title = 8,
  field_value = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_description] = "description",
  [field_id] = "id",
  [field_key] = "key",
  [field_kind] = "kind",
  [field_name] = "name",
  [field_path] = "path",
  [field_selective] = "selective",
  [field_title] = "title",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 1},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 2},
  [7] = {.index = 10, .length = 3},
  [8] = {.index = 13, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_path, 1},
  [1] =
    {field_path, 1},
    {field_selective, 2},
  [3] =
    {field_id, 1},
    {field_title, 2},
  [5] =
    {field_name, 1},
  [6] =
    {field_kind, 0},
    {field_name, 1},
  [8] =
    {field_key, 0},
    {field_value, 1},
  [10] =
    {field_kind, 0},
    {field_name, 1},
    {field_title, 2},
  [13] =
    {field_description, 2},
    {field_kind, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
};

static const TSCharacterRange sym_scheme_ref_id_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '!'}, {'#', '\''}, {'*', '+'}, {'-', 'Z'}, {'\\', '\\'}, {'^', 'z'},
  {'|', '|'}, {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(18);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == ',') ADVANCE(22);
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == '[') ADVANCE(25);
      if (lookahead == ']') ADVANCE(26);
      if (lookahead == '{') ADVANCE(21);
      if (lookahead == '}') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(29);
      if (lookahead == '\\') ADVANCE(17);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(28);
      if (lookahead == '\\') ADVANCE(17);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(30);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(13);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(19);
      END_STATE();
    case 9:
      if (lookahead == ':') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 14:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 15:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 16:
      if ((!eof && set_contains(sym_scheme_ref_id_character_set_1, 10, lookahead))) ADVANCE(24);
      END_STATE();
    case 17:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_import_path);
      if (lookahead == '/') ADVANCE(15);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_scheme_ref_id);
      if ((!eof && set_contains(sym_scheme_ref_id_character_set_1, 10, lookahead))) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '"') ADVANCE(5);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_triple_quoted_string);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_date_literal);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '-') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'd') ADVANCE(1);
      if (lookahead == 'f') ADVANCE(2);
      if (lookahead == 'r') ADVANCE(3);
      if (lookahead == 's') ADVANCE(4);
      if (lookahead == 't') ADVANCE(5);
      if (lookahead == 'u') ADVANCE(6);
      if (lookahead == 'v') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(9);
      END_STATE();
    case 3:
      if (lookahead == 'e') ADVANCE(10);
      END_STATE();
    case 4:
      if (lookahead == 'p') ADVANCE(11);
      END_STATE();
    case 5:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 6:
      if (lookahead == 's') ADVANCE(13);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 8:
      if (lookahead == 'f') ADVANCE(15);
      END_STATE();
    case 9:
      if (lookahead == 'l') ADVANCE(16);
      END_STATE();
    case 10:
      if (lookahead == 'f') ADVANCE(17);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 12:
      if (lookahead == 'u') ADVANCE(19);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 14:
      if (lookahead == 'r') ADVANCE(21);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(22);
      END_STATE();
    case 16:
      if (lookahead == 's') ADVANCE(23);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_ref);
      END_STATE();
    case 18:
      if (lookahead == 'c') ADVANCE(24);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_use);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(26);
      END_STATE();
    case 22:
      if (lookahead == 'n') ADVANCE(27);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_spec);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 26:
      if (lookahead == 'f') ADVANCE(29);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(30);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 29:
      if (lookahead == 'y') ADVANCE(31);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_define);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_verify);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 7},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_use] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_spec] = ACTIONS(1),
    [anon_sym_ref] = ACTIONS(1),
    [anon_sym_define] = ACTIONS(1),
    [anon_sym_verify] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_triple_quoted_string] = ACTIONS(1),
    [sym_date_literal] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(64),
    [sym_use_import] = STATE(2),
    [sym__block] = STATE(2),
    [sym_entity_block] = STATE(2),
    [sym_spec_block] = STATE(2),
    [sym_ref_block] = STATE(2),
    [sym_ref_inline] = STATE(9),
    [sym_ref_full] = STATE(9),
    [sym_define_block] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [anon_sym_use] = ACTIONS(9),
    [anon_sym_spec] = ACTIONS(11),
    [anon_sym_ref] = ACTIONS(13),
    [anon_sym_define] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_use,
    ACTIONS(11), 1,
      anon_sym_spec,
    ACTIONS(13), 1,
      anon_sym_ref,
    ACTIONS(15), 1,
      anon_sym_define,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    STATE(9), 2,
      sym_ref_inline,
      sym_ref_full,
    STATE(3), 7,
      sym_use_import,
      sym__block,
      sym_entity_block,
      sym_spec_block,
      sym_ref_block,
      sym_define_block,
      aux_sym_source_file_repeat1,
  [35] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(24), 1,
      anon_sym_use,
    ACTIONS(27), 1,
      anon_sym_spec,
    ACTIONS(30), 1,
      anon_sym_ref,
    ACTIONS(33), 1,
      anon_sym_define,
    STATE(9), 2,
      sym_ref_inline,
      sym_ref_full,
    STATE(3), 7,
      sym_use_import,
      sym__block,
      sym_entity_block,
      sym_spec_block,
      sym_ref_block,
      sym_define_block,
      aux_sym_source_file_repeat1,
  [70] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(38), 1,
      anon_sym_LBRACE,
    ACTIONS(40), 1,
      anon_sym_LBRACK,
    ACTIONS(42), 2,
      sym_triple_quoted_string,
      sym_date_literal,
    ACTIONS(44), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(36), 3,
      sym_identifier,
      sym_string,
      sym_integer,
    STATE(41), 4,
      sym__value,
      sym_list,
      sym_nested_block,
      sym_boolean,
  [99] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      ts_builtin_sym_end,
    ACTIONS(50), 1,
      anon_sym_LBRACE,
    STATE(15), 1,
      sym_selective_import,
    ACTIONS(48), 5,
      anon_sym_use,
      anon_sym_spec,
      anon_sym_ref,
      anon_sym_define,
      sym_identifier,
  [119] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(52), 1,
      ts_builtin_sym_end,
    ACTIONS(56), 1,
      anon_sym_LBRACE,
    ACTIONS(54), 5,
      anon_sym_use,
      anon_sym_spec,
      anon_sym_ref,
      anon_sym_define,
      sym_identifier,
  [136] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      sym_identifier,
    ACTIONS(60), 1,
      anon_sym_COMMA,
    ACTIONS(64), 1,
      anon_sym_RBRACK,
    STATE(47), 1,
      sym__list_item,
    ACTIONS(62), 3,
      sym_scheme_ref_id,
      sym_string,
      sym_integer,
  [157] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      ts_builtin_sym_end,
    ACTIONS(68), 5,
      anon_sym_use,
      anon_sym_spec,
      anon_sym_ref,
      anon_sym_define,
      sym_identifier,
  [171] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      ts_builtin_sym_end,
    ACTIONS(72), 5,
      anon_sym_use,
      anon_sym_spec,
      anon_sym_ref,
      anon_sym_define,
      sym_identifier,
  [185] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      ts_builtin_sym_end,
    ACTIONS(76), 5,
      anon_sym_use,
      anon_sym_spec,
      anon_sym_ref,
      anon_sym_define,
      sym_identifier,
  [199] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(80), 1,
      anon_sym_RBRACE,
    ACTIONS(82), 1,
      anon_sym_verify,
    STATE(12), 3,
      sym_field,
      sym_verify_statement,
      aux_sym_entity_block_repeat1,
  [217] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(82), 1,
      anon_sym_verify,
    ACTIONS(84), 1,
      anon_sym_RBRACE,
    STATE(22), 3,
      sym_field,
      sym_verify_statement,
      aux_sym_entity_block_repeat1,
  [235] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(82), 1,
      anon_sym_verify,
    ACTIONS(86), 1,
      anon_sym_RBRACE,
    STATE(22), 3,
      sym_field,
      sym_verify_statement,
      aux_sym_entity_block_repeat1,
  [253] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      ts_builtin_sym_end,
    ACTIONS(90), 5,
      anon_sym_use,
      anon_sym_spec,
      anon_sym_ref,
      anon_sym_define,
      sym_identifier,
  [267] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      ts_builtin_sym_end,
    ACTIONS(94), 5,
      anon_sym_use,
      anon_sym_spec,
      anon_sym_ref,
      anon_sym_define,
      sym_identifier,
  [281] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      ts_builtin_sym_end,
    ACTIONS(98), 5,
      anon_sym_use,
      anon_sym_spec,
      anon_sym_ref,
      anon_sym_define,
      sym_identifier,
  [295] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(82), 1,
      anon_sym_verify,
    ACTIONS(100), 1,
      anon_sym_RBRACE,
    STATE(22), 3,
      sym_field,
      sym_verify_statement,
      aux_sym_entity_block_repeat1,
  [313] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(82), 1,
      anon_sym_verify,
    ACTIONS(102), 1,
      anon_sym_RBRACE,
    STATE(28), 3,
      sym_field,
      sym_verify_statement,
      aux_sym_entity_block_repeat1,
  [331] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      ts_builtin_sym_end,
    ACTIONS(106), 5,
      anon_sym_use,
      anon_sym_spec,
      anon_sym_ref,
      anon_sym_define,
      sym_identifier,
  [345] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(82), 1,
      anon_sym_verify,
    ACTIONS(108), 1,
      anon_sym_RBRACE,
    STATE(13), 3,
      sym_field,
      sym_verify_statement,
      aux_sym_entity_block_repeat1,
  [363] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 1,
      ts_builtin_sym_end,
    ACTIONS(112), 5,
      anon_sym_use,
      anon_sym_spec,
      anon_sym_ref,
      anon_sym_define,
      sym_identifier,
  [377] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      sym_identifier,
    ACTIONS(117), 1,
      anon_sym_RBRACE,
    ACTIONS(119), 1,
      anon_sym_verify,
    STATE(22), 3,
      sym_field,
      sym_verify_statement,
      aux_sym_entity_block_repeat1,
  [395] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 1,
      ts_builtin_sym_end,
    ACTIONS(124), 5,
      anon_sym_use,
      anon_sym_spec,
      anon_sym_ref,
      anon_sym_define,
      sym_identifier,
  [409] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 1,
      ts_builtin_sym_end,
    ACTIONS(128), 5,
      anon_sym_use,
      anon_sym_spec,
      anon_sym_ref,
      anon_sym_define,
      sym_identifier,
  [423] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      ts_builtin_sym_end,
    ACTIONS(132), 5,
      anon_sym_use,
      anon_sym_spec,
      anon_sym_ref,
      anon_sym_define,
      sym_identifier,
  [437] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(82), 1,
      anon_sym_verify,
    ACTIONS(134), 1,
      anon_sym_RBRACE,
    STATE(17), 3,
      sym_field,
      sym_verify_statement,
      aux_sym_entity_block_repeat1,
  [455] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 1,
      ts_builtin_sym_end,
    ACTIONS(138), 5,
      anon_sym_use,
      anon_sym_spec,
      anon_sym_ref,
      anon_sym_define,
      sym_identifier,
  [469] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      sym_identifier,
    ACTIONS(82), 1,
      anon_sym_verify,
    ACTIONS(140), 1,
      anon_sym_RBRACE,
    STATE(22), 3,
      sym_field,
      sym_verify_statement,
      aux_sym_entity_block_repeat1,
  [487] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      ts_builtin_sym_end,
    ACTIONS(144), 5,
      anon_sym_use,
      anon_sym_spec,
      anon_sym_ref,
      anon_sym_define,
      sym_identifier,
  [501] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 1,
      ts_builtin_sym_end,
    ACTIONS(148), 5,
      anon_sym_use,
      anon_sym_spec,
      anon_sym_ref,
      anon_sym_define,
      sym_identifier,
  [515] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 1,
      sym_identifier,
    ACTIONS(154), 1,
      anon_sym_RBRACK,
    STATE(56), 1,
      sym__list_item,
    ACTIONS(152), 3,
      sym_scheme_ref_id,
      sym_string,
      sym_integer,
  [533] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 1,
      sym_identifier,
    ACTIONS(156), 1,
      anon_sym_RBRACK,
    STATE(56), 1,
      sym__list_item,
    ACTIONS(152), 3,
      sym_scheme_ref_id,
      sym_string,
      sym_integer,
  [551] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 1,
      sym_identifier,
    STATE(56), 1,
      sym__list_item,
    ACTIONS(152), 3,
      sym_scheme_ref_id,
      sym_string,
      sym_integer,
  [566] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 1,
      sym_identifier,
    ACTIONS(160), 1,
      anon_sym_RBRACE,
    STATE(36), 2,
      sym_field,
      aux_sym_ref_full_repeat1,
  [580] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 1,
      sym_identifier,
    ACTIONS(162), 1,
      anon_sym_RBRACE,
    STATE(37), 2,
      sym_field,
      aux_sym_ref_full_repeat1,
  [594] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 1,
      sym_identifier,
    ACTIONS(164), 1,
      anon_sym_RBRACE,
    STATE(38), 2,
      sym_field,
      aux_sym_ref_full_repeat1,
  [608] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 1,
      sym_identifier,
    ACTIONS(166), 1,
      anon_sym_RBRACE,
    STATE(38), 2,
      sym_field,
      aux_sym_ref_full_repeat1,
  [622] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      sym_identifier,
    ACTIONS(171), 1,
      anon_sym_RBRACE,
    STATE(38), 2,
      sym_field,
      aux_sym_ref_full_repeat1,
  [636] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      anon_sym_RBRACE,
    ACTIONS(173), 2,
      anon_sym_verify,
      sym_identifier,
  [647] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      anon_sym_COMMA,
    ACTIONS(179), 1,
      anon_sym_RBRACE,
    STATE(45), 1,
      aux_sym_selective_import_repeat1,
  [660] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      anon_sym_RBRACE,
    ACTIONS(181), 2,
      anon_sym_verify,
      sym_identifier,
  [671] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      anon_sym_COMMA,
    ACTIONS(188), 1,
      anon_sym_RBRACE,
    STATE(42), 1,
      aux_sym_selective_import_repeat1,
  [684] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 1,
      anon_sym_RBRACE,
    ACTIONS(190), 2,
      anon_sym_verify,
      sym_identifier,
  [695] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 1,
      anon_sym_RBRACE,
    ACTIONS(194), 2,
      anon_sym_verify,
      sym_identifier,
  [706] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      anon_sym_COMMA,
    ACTIONS(198), 1,
      anon_sym_RBRACE,
    STATE(42), 1,
      aux_sym_selective_import_repeat1,
  [719] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 1,
      anon_sym_RBRACE,
    ACTIONS(200), 2,
      anon_sym_verify,
      sym_identifier,
  [730] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      anon_sym_COMMA,
    ACTIONS(206), 1,
      anon_sym_RBRACK,
    STATE(50), 1,
      aux_sym_list_repeat1,
  [743] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      anon_sym_RBRACE,
    ACTIONS(208), 2,
      anon_sym_verify,
      sym_identifier,
  [754] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 1,
      anon_sym_RBRACE,
    ACTIONS(212), 2,
      anon_sym_verify,
      sym_identifier,
  [765] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 1,
      anon_sym_RBRACK,
    ACTIONS(216), 1,
      anon_sym_COMMA,
    STATE(52), 1,
      aux_sym_list_repeat1,
  [778] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      anon_sym_RBRACE,
    ACTIONS(218), 2,
      anon_sym_verify,
      sym_identifier,
  [789] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      anon_sym_COMMA,
    ACTIONS(225), 1,
      anon_sym_RBRACK,
    STATE(52), 1,
      aux_sym_list_repeat1,
  [802] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      anon_sym_RBRACE,
    ACTIONS(227), 2,
      anon_sym_verify,
      sym_identifier,
  [813] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [821] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_LBRACE,
    ACTIONS(233), 1,
      sym_string,
  [831] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [839] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      anon_sym_LBRACE,
  [846] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      sym_identifier,
  [853] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      anon_sym_LBRACE,
  [860] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      sym_string,
  [867] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      sym_identifier,
  [874] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      sym_identifier,
  [881] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      sym_identifier,
  [888] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      ts_builtin_sym_end,
  [895] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      sym_import_path,
  [902] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 1,
      anon_sym_RBRACK,
  [909] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      sym_identifier,
  [916] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 1,
      sym_string,
  [923] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      sym_string,
  [930] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      sym_scheme_ref_id,
  [937] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      anon_sym_LBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 35,
  [SMALL_STATE(4)] = 70,
  [SMALL_STATE(5)] = 99,
  [SMALL_STATE(6)] = 119,
  [SMALL_STATE(7)] = 136,
  [SMALL_STATE(8)] = 157,
  [SMALL_STATE(9)] = 171,
  [SMALL_STATE(10)] = 185,
  [SMALL_STATE(11)] = 199,
  [SMALL_STATE(12)] = 217,
  [SMALL_STATE(13)] = 235,
  [SMALL_STATE(14)] = 253,
  [SMALL_STATE(15)] = 267,
  [SMALL_STATE(16)] = 281,
  [SMALL_STATE(17)] = 295,
  [SMALL_STATE(18)] = 313,
  [SMALL_STATE(19)] = 331,
  [SMALL_STATE(20)] = 345,
  [SMALL_STATE(21)] = 363,
  [SMALL_STATE(22)] = 377,
  [SMALL_STATE(23)] = 395,
  [SMALL_STATE(24)] = 409,
  [SMALL_STATE(25)] = 423,
  [SMALL_STATE(26)] = 437,
  [SMALL_STATE(27)] = 455,
  [SMALL_STATE(28)] = 469,
  [SMALL_STATE(29)] = 487,
  [SMALL_STATE(30)] = 501,
  [SMALL_STATE(31)] = 515,
  [SMALL_STATE(32)] = 533,
  [SMALL_STATE(33)] = 551,
  [SMALL_STATE(34)] = 566,
  [SMALL_STATE(35)] = 580,
  [SMALL_STATE(36)] = 594,
  [SMALL_STATE(37)] = 608,
  [SMALL_STATE(38)] = 622,
  [SMALL_STATE(39)] = 636,
  [SMALL_STATE(40)] = 647,
  [SMALL_STATE(41)] = 660,
  [SMALL_STATE(42)] = 671,
  [SMALL_STATE(43)] = 684,
  [SMALL_STATE(44)] = 695,
  [SMALL_STATE(45)] = 706,
  [SMALL_STATE(46)] = 719,
  [SMALL_STATE(47)] = 730,
  [SMALL_STATE(48)] = 743,
  [SMALL_STATE(49)] = 754,
  [SMALL_STATE(50)] = 765,
  [SMALL_STATE(51)] = 778,
  [SMALL_STATE(52)] = 789,
  [SMALL_STATE(53)] = 802,
  [SMALL_STATE(54)] = 813,
  [SMALL_STATE(55)] = 821,
  [SMALL_STATE(56)] = 831,
  [SMALL_STATE(57)] = 839,
  [SMALL_STATE(58)] = 846,
  [SMALL_STATE(59)] = 853,
  [SMALL_STATE(60)] = 860,
  [SMALL_STATE(61)] = 867,
  [SMALL_STATE(62)] = 874,
  [SMALL_STATE(63)] = 881,
  [SMALL_STATE(64)] = 888,
  [SMALL_STATE(65)] = 895,
  [SMALL_STATE(66)] = 902,
  [SMALL_STATE(67)] = 909,
  [SMALL_STATE(68)] = 916,
  [SMALL_STATE(69)] = 923,
  [SMALL_STATE(70)] = 930,
  [SMALL_STATE(71)] = 937,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [24] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [36] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_use_import, 2, 0, 1),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_use_import, 2, 0, 1),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ref_inline, 3, 0, 3),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ref_inline, 3, 0, 3),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_block, 5, 0, 5),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entity_block, 5, 0, 5),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ref_block, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ref_block, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_spec_block, 4, 0, 4),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_spec_block, 4, 0, 4),
  [78] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [82] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_define_block, 4, 0, 4),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_define_block, 4, 0, 4),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_use_import, 3, 0, 2),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_use_import, 3, 0, 2),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_block, 4, 0, 5),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entity_block, 4, 0, 5),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selective_import, 3, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_selective_import, 3, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_spec_block, 5, 0, 4),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_spec_block, 5, 0, 4),
  [114] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_entity_block_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_entity_block_repeat1, 2, 0, 0),
  [119] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_entity_block_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ref_full, 5, 0, 3),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ref_full, 5, 0, 3),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ref_full, 6, 0, 3),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ref_full, 6, 0, 3),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_define_block, 5, 0, 4),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_define_block, 5, 0, 4),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_block, 5, 0, 7),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entity_block, 5, 0, 7),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selective_import, 4, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_selective_import, 4, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_block, 6, 0, 7),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entity_block, 6, 0, 7),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [168] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ref_full_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_ref_full_repeat1, 2, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field, 2, 0, 6),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 2, 0, 6),
  [185] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_selective_import_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_selective_import_repeat1, 2, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_verify_statement, 3, 0, 8),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verify_statement, 3, 0, 8),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_nested_block, 2, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nested_block, 2, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_nested_block, 3, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nested_block, 3, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [218] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 4, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4, 0, 0),
  [222] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 5, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 5, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [249] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_specforge(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "specforge",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
