/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 86
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 55
#define ALIAS_COUNT 0
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 11
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 12
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_comment = 2,
  anon_sym_use = 3,
  sym_import_path = 4,
  anon_sym_LBRACE = 5,
  anon_sym_COMMA = 6,
  anon_sym_RBRACE = 7,
  anon_sym_spec = 8,
  anon_sym_ref = 9,
  sym_scheme_ref_id = 10,
  anon_sym_define = 11,
  anon_sym_EQ = 12,
  anon_sym_PIPE = 13,
  sym_negative_integer = 14,
  aux_sym_annotation_token1 = 15,
  anon_sym_LBRACK_RBRACK = 16,
  anon_sym_verify = 17,
  anon_sym_LBRACK = 18,
  anon_sym_RBRACK = 19,
  sym_string = 20,
  sym_triple_quoted_string = 21,
  sym_date_literal = 22,
  sym_integer = 23,
  anon_sym_true = 24,
  anon_sym_false = 25,
  sym_source_file = 26,
  sym_use_import = 27,
  sym_selective_import = 28,
  sym__block = 29,
  sym_entity_block = 30,
  sym_spec_block = 31,
  sym_ref_block = 32,
  sym_ref_inline = 33,
  sym_ref_full = 34,
  sym_define_block = 35,
  sym_union_block = 36,
  sym_union_variants = 37,
  sym__union_variant = 38,
  sym_field = 39,
  sym_annotation = 40,
  sym__value = 41,
  sym_array_type = 42,
  sym_verify_statement = 43,
  sym_list = 44,
  sym__list_item = 45,
  sym_nested_block = 46,
  sym_boolean = 47,
  aux_sym_source_file_repeat1 = 48,
  aux_sym_selective_import_repeat1 = 49,
  aux_sym_entity_block_repeat1 = 50,
  aux_sym_ref_full_repeat1 = 51,
  aux_sym_union_variants_repeat1 = 52,
  aux_sym_field_repeat1 = 53,
  aux_sym_list_repeat1 = 54,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [anon_sym_use] = "use",
  [sym_import_path] = "import_path",
  [anon_sym_LBRACE] = "{",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACE] = "}",
  [anon_sym_spec] = "spec",
  [anon_sym_ref] = "ref",
  [sym_scheme_ref_id] = "scheme_ref_id",
  [anon_sym_define] = "define",
  [anon_sym_EQ] = "=",
  [anon_sym_PIPE] = "|",
  [sym_negative_integer] = "negative_integer",
  [aux_sym_annotation_token1] = "annotation_token1",
  [anon_sym_LBRACK_RBRACK] = "[]",
  [anon_sym_verify] = "verify",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_string] = "string",
  [sym_triple_quoted_string] = "triple_quoted_string",
  [sym_date_literal] = "date_literal",
  [sym_integer] = "integer",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_source_file] = "source_file",
  [sym_use_import] = "use_import",
  [sym_selective_import] = "selective_import",
  [sym__block] = "_block",
  [sym_entity_block] = "entity_block",
  [sym_spec_block] = "spec_block",
  [sym_ref_block] = "ref_block",
  [sym_ref_inline] = "ref_inline",
  [sym_ref_full] = "ref_full",
  [sym_define_block] = "define_block",
  [sym_union_block] = "union_block",
  [sym_union_variants] = "union_variants",
  [sym__union_variant] = "_union_variant",
  [sym_field] = "field",
  [sym_annotation] = "annotation",
  [sym__value] = "_value",
  [sym_array_type] = "array_type",
  [sym_verify_statement] = "verify_statement",
  [sym_list] = "list",
  [sym__list_item] = "_list_item",
  [sym_nested_block] = "nested_block",
  [sym_boolean] = "boolean",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_selective_import_repeat1] = "selective_import_repeat1",
  [aux_sym_entity_block_repeat1] = "entity_block_repeat1",
  [aux_sym_ref_full_repeat1] = "ref_full_repeat1",
  [aux_sym_union_variants_repeat1] = "union_variants_repeat1",
  [aux_sym_field_repeat1] = "field_repeat1",
  [aux_sym_list_repeat1] = "list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [anon_sym_use] = anon_sym_use,
  [sym_import_path] = sym_import_path,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_spec] = anon_sym_spec,
  [anon_sym_ref] = anon_sym_ref,
  [sym_scheme_ref_id] = sym_scheme_ref_id,
  [anon_sym_define] = anon_sym_define,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym_negative_integer] = sym_negative_integer,
  [aux_sym_annotation_token1] = aux_sym_annotation_token1,
  [anon_sym_LBRACK_RBRACK] = anon_sym_LBRACK_RBRACK,
  [anon_sym_verify] = anon_sym_verify,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_string] = sym_string,
  [sym_triple_quoted_string] = sym_triple_quoted_string,
  [sym_date_literal] = sym_date_literal,
  [sym_integer] = sym_integer,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_source_file] = sym_source_file,
  [sym_use_import] = sym_use_import,
  [sym_selective_import] = sym_selective_import,
  [sym__block] = sym__block,
  [sym_entity_block] = sym_entity_block,
  [sym_spec_block] = sym_spec_block,
  [sym_ref_block] = sym_ref_block,
  [sym_ref_inline] = sym_ref_inline,
  [sym_ref_full] = sym_ref_full,
  [sym_define_block] = sym_define_block,
  [sym_union_block] = sym_union_block,
  [sym_union_variants] = sym_union_variants,
  [sym__union_variant] = sym__union_variant,
  [sym_field] = sym_field,
  [sym_annotation] = sym_annotation,
  [sym__value] = sym__value,
  [sym_array_type] = sym_array_type,
  [sym_verify_statement] = sym_verify_statement,
  [sym_list] = sym_list,
  [sym__list_item] = sym__list_item,
  [sym_nested_block] = sym_nested_block,
  [sym_boolean] = sym_boolean,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_selective_import_repeat1] = aux_sym_selective_import_repeat1,
  [aux_sym_entity_block_repeat1] = aux_sym_entity_block_repeat1,
  [aux_sym_ref_full_repeat1] = aux_sym_ref_full_repeat1,
  [aux_sym_union_variants_repeat1] = aux_sym_union_variants_repeat1,
  [aux_sym_field_repeat1] = aux_sym_field_repeat1,
  [aux_sym_list_repeat1] = aux_sym_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_use] = {
    .visible = true,
    .named = false,
  },
  [sym_import_path] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_spec] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ref] = {
    .visible = true,
    .named = false,
  },
  [sym_scheme_ref_id] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_define] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_negative_integer] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_annotation_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_verify] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_triple_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_date_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_use_import] = {
    .visible = true,
    .named = true,
  },
  [sym_selective_import] = {
    .visible = true,
    .named = true,
  },
  [sym__block] = {
    .visible = false,
    .named = true,
  },
  [sym_entity_block] = {
    .visible = true,
    .named = true,
  },
  [sym_spec_block] = {
    .visible = true,
    .named = true,
  },
  [sym_ref_block] = {
    .visible = true,
    .named = true,
  },
  [sym_ref_inline] = {
    .visible = true,
    .named = true,
  },
  [sym_ref_full] = {
    .visible = true,
    .named = true,
  },
  [sym_define_block] = {
    .visible = true,
    .named = true,
  },
  [sym_union_block] = {
    .visible = true,
    .named = true,
  },
  [sym_union_variants] = {
    .visible = true,
    .named = true,
  },
  [sym__union_variant] = {
    .visible = false,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_annotation] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_array_type] = {
    .visible = true,
    .named = true,
  },
  [sym_verify_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym__list_item] = {
    .visible = false,
    .named = true,
  },
  [sym_nested_block] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_selective_import_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_entity_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_ref_full_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_union_variants_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_field_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_description = 1,
  field_element = 2,
  field_id = 3,
  field_key = 4,
  field_kind = 5,
  field_name = 6,
  field_path = 7,
  field_selective = 8,
  field_title = 9,
  field_value = 10,
  field_variants = 11,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_description] = "description",
  [field_element] = "element",
  [field_id] = "id",
  [field_key] = "key",
  [field_kind] = "kind",
  [field_name] = "name",
  [field_path] = "path",
  [field_selective] = "selective",
  [field_title] = "title",
  [field_value] = "value",
  [field_variants] = "variants",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 1},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 3},
  [7] = {.index = 11, .length = 1},
  [8] = {.index = 12, .length = 2},
  [9] = {.index = 14, .length = 3},
  [10] = {.index = 17, .length = 2},
  [11] = {.index = 19, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_path, 1},
  [1] =
    {field_path, 1},
    {field_selective, 2},
  [3] =
    {field_id, 1},
    {field_title, 2},
  [5] =
    {field_name, 1},
  [6] =
    {field_kind, 0},
    {field_name, 1},
  [8] =
    {field_kind, 0},
    {field_name, 1},
    {field_variants, 3},
  [11] =
    {field_description, 1},
  [12] =
    {field_key, 0},
    {field_value, 1},
  [14] =
    {field_kind, 0},
    {field_name, 1},
    {field_title, 2},
  [17] =
    {field_description, 2},
    {field_kind, 1},
  [19] =
    {field_element, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
};

static const TSCharacterRange sym_scheme_ref_id_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '!'}, {'#', '\''}, {'*', '+'}, {'-', 'Z'}, {'\\', '\\'}, {'^', 'z'},
  {'|', '|'}, {'~', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(23);
      ADVANCE_MAP(
        '"', 1,
        ',', 27,
        '-', 13,
        '/', 10,
        '=', 30,
        '@', 18,
        '[', 35,
        ']', 36,
        '{', 26,
        '|', 31,
        '}', 28,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(40);
      if (lookahead == '\\') ADVANCE(22);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(39);
      if (lookahead == '\\') ADVANCE(22);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(41);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(10);
      if (lookahead == '@') ADVANCE(18);
      if (lookahead == '[') ADVANCE(12);
      if (lookahead == '}') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(10);
      if (lookahead == '@') ADVANCE(18);
      if (lookahead == '}') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 9:
      if (lookahead == '/') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(24);
      END_STATE();
    case 11:
      if (lookahead == ':') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 12:
      if (lookahead == ']') ADVANCE(34);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 18:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 19:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(11);
      END_STATE();
    case 20:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 21:
      if ((!eof && set_contains(sym_scheme_ref_id_character_set_1, 10, lookahead))) ADVANCE(29);
      END_STATE();
    case 22:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_import_path);
      if (lookahead == '/') ADVANCE(20);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_scheme_ref_id);
      if ((!eof && set_contains(sym_scheme_ref_id_character_set_1, 10, lookahead))) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_negative_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_annotation_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LBRACK_RBRACK);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '.') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '"') ADVANCE(5);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_triple_quoted_string);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_date_literal);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '-') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'd') ADVANCE(1);
      if (lookahead == 'f') ADVANCE(2);
      if (lookahead == 'r') ADVANCE(3);
      if (lookahead == 's') ADVANCE(4);
      if (lookahead == 't') ADVANCE(5);
      if (lookahead == 'u') ADVANCE(6);
      if (lookahead == 'v') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(9);
      END_STATE();
    case 3:
      if (lookahead == 'e') ADVANCE(10);
      END_STATE();
    case 4:
      if (lookahead == 'p') ADVANCE(11);
      END_STATE();
    case 5:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 6:
      if (lookahead == 's') ADVANCE(13);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 8:
      if (lookahead == 'f') ADVANCE(15);
      END_STATE();
    case 9:
      if (lookahead == 'l') ADVANCE(16);
      END_STATE();
    case 10:
      if (lookahead == 'f') ADVANCE(17);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 12:
      if (lookahead == 'u') ADVANCE(19);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 14:
      if (lookahead == 'r') ADVANCE(21);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(22);
      END_STATE();
    case 16:
      if (lookahead == 's') ADVANCE(23);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_ref);
      END_STATE();
    case 18:
      if (lookahead == 'c') ADVANCE(24);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_use);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(26);
      END_STATE();
    case 22:
      if (lookahead == 'n') ADVANCE(27);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_spec);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 26:
      if (lookahead == 'f') ADVANCE(29);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(30);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 29:
      if (lookahead == 'y') ADVANCE(31);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_define);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_verify);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 7},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 9},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_use] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_spec] = ACTIONS(1),
    [anon_sym_ref] = ACTIONS(1),
    [anon_sym_define] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym_negative_integer] = ACTIONS(1),
    [aux_sym_annotation_token1] = ACTIONS(1),
    [anon_sym_verify] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_triple_quoted_string] = ACTIONS(1),
    [sym_date_literal] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(74),
    [sym_use_import] = STATE(3),
    [sym__block] = STATE(3),
    [sym_entity_block] = STATE(3),
    [sym_spec_block] = STATE(3),
    [sym_ref_block] = STATE(3),
    [sym_ref_inline] = STATE(27),
    [sym_ref_full] = STATE(27),
    [sym_define_block] = STATE(3),
    [sym_union_block] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [anon_sym_use] = ACTIONS(9),
    [anon_sym_spec] = ACTIONS(11),
    [anon_sym_ref] = ACTIONS(13),
    [anon_sym_define] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(22), 1,
      anon_sym_use,
    ACTIONS(25), 1,
      anon_sym_spec,
    ACTIONS(28), 1,
      anon_sym_ref,
    ACTIONS(31), 1,
      anon_sym_define,
    STATE(27), 2,
      sym_ref_inline,
      sym_ref_full,
    STATE(2), 8,
      sym_use_import,
      sym__block,
      sym_entity_block,
      sym_spec_block,
      sym_ref_block,
      sym_define_block,
      sym_union_block,
      aux_sym_source_file_repeat1,
  [36] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_use,
    ACTIONS(11), 1,
      anon_sym_spec,
    ACTIONS(13), 1,
      anon_sym_ref,
    ACTIONS(15), 1,
      anon_sym_define,
    ACTIONS(34), 1,
      ts_builtin_sym_end,
    STATE(27), 2,
      sym_ref_inline,
      sym_ref_full,
    STATE(2), 8,
      sym_use_import,
      sym__block,
      sym_entity_block,
      sym_spec_block,
      sym_ref_block,
      sym_define_block,
      sym_union_block,
      aux_sym_source_file_repeat1,
  [72] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(36), 1,
      sym_identifier,
    ACTIONS(38), 1,
      anon_sym_LBRACE,
    ACTIONS(40), 1,
      anon_sym_LBRACK,
    ACTIONS(42), 2,
      sym_string,
      sym_integer,
    ACTIONS(44), 2,
      sym_triple_quoted_string,
      sym_date_literal,
    ACTIONS(46), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 5,
      sym__value,
      sym_array_type,
      sym_list,
      sym_nested_block,
      sym_boolean,
  [104] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 1,
      ts_builtin_sym_end,
    ACTIONS(52), 1,
      anon_sym_LBRACE,
    STATE(18), 1,
      sym_selective_import,
    ACTIONS(50), 5,
      anon_sym_use,
      anon_sym_spec,
      anon_sym_ref,
      anon_sym_define,
      sym_identifier,
  [124] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 1,
      ts_builtin_sym_end,
    ACTIONS(58), 1,
      anon_sym_PIPE,
    STATE(6), 1,
      aux_sym_union_variants_repeat1,
    ACTIONS(56), 5,
      anon_sym_use,
      anon_sym_spec,
      anon_sym_ref,
      anon_sym_define,
      sym_identifier,
  [144] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 1,
      ts_builtin_sym_end,
    ACTIONS(65), 1,
      anon_sym_PIPE,
    STATE(8), 1,
      aux_sym_union_variants_repeat1,
    ACTIONS(63), 5,
      anon_sym_use,
      anon_sym_spec,
      anon_sym_ref,
      anon_sym_define,
      sym_identifier,
  [164] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      anon_sym_PIPE,
    ACTIONS(67), 1,
      ts_builtin_sym_end,
    STATE(6), 1,
      aux_sym_union_variants_repeat1,
    ACTIONS(69), 5,
      anon_sym_use,
      anon_sym_spec,
      anon_sym_ref,
      anon_sym_define,
      sym_identifier,
  [184] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      ts_builtin_sym_end,
    ACTIONS(75), 1,
      anon_sym_LBRACE,
    ACTIONS(73), 5,
      anon_sym_use,
      anon_sym_spec,
      anon_sym_ref,
      anon_sym_define,
      sym_identifier,
  [201] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      sym_identifier,
    ACTIONS(79), 1,
      anon_sym_COMMA,
    ACTIONS(83), 1,
      anon_sym_RBRACK,
    STATE(63), 1,
      sym__list_item,
    ACTIONS(81), 3,
      sym_scheme_ref_id,
      sym_string,
      sym_integer,
  [222] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 2,
      ts_builtin_sym_end,
      anon_sym_PIPE,
    ACTIONS(56), 5,
      anon_sym_use,
      anon_sym_spec,
      anon_sym_ref,
      anon_sym_define,
      sym_identifier,
  [237] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      sym_identifier,
    ACTIONS(87), 1,
      anon_sym_RBRACE,
    ACTIONS(89), 1,
      anon_sym_verify,
    STATE(30), 3,
      sym_field,
      sym_verify_statement,
      aux_sym_entity_block_repeat1,
  [255] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      ts_builtin_sym_end,
    ACTIONS(93), 5,
      anon_sym_use,
      anon_sym_spec,
      anon_sym_ref,
      anon_sym_define,
      sym_identifier,
  [269] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      sym_identifier,
    ACTIONS(89), 1,
      anon_sym_verify,
    ACTIONS(95), 1,
      anon_sym_RBRACE,
    STATE(24), 3,
      sym_field,
      sym_verify_statement,
      aux_sym_entity_block_repeat1,
  [287] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      ts_builtin_sym_end,
    ACTIONS(99), 5,
      anon_sym_use,
      anon_sym_spec,
      anon_sym_ref,
      anon_sym_define,
      sym_identifier,
  [301] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      sym_identifier,
    ACTIONS(89), 1,
      anon_sym_verify,
    ACTIONS(101), 1,
      anon_sym_RBRACE,
    STATE(24), 3,
      sym_field,
      sym_verify_statement,
      aux_sym_entity_block_repeat1,
  [319] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      ts_builtin_sym_end,
    ACTIONS(105), 5,
      anon_sym_use,
      anon_sym_spec,
      anon_sym_ref,
      anon_sym_define,
      sym_identifier,
  [333] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      ts_builtin_sym_end,
    ACTIONS(109), 5,
      anon_sym_use,
      anon_sym_spec,
      anon_sym_ref,
      anon_sym_define,
      sym_identifier,
  [347] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      sym_identifier,
    ACTIONS(89), 1,
      anon_sym_verify,
    ACTIONS(111), 1,
      anon_sym_RBRACE,
    STATE(14), 3,
      sym_field,
      sym_verify_statement,
      aux_sym_entity_block_repeat1,
  [365] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      ts_builtin_sym_end,
    ACTIONS(115), 5,
      anon_sym_use,
      anon_sym_spec,
      anon_sym_ref,
      anon_sym_define,
      sym_identifier,
  [379] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      sym_identifier,
    ACTIONS(89), 1,
      anon_sym_verify,
    ACTIONS(117), 1,
      anon_sym_RBRACE,
    STATE(16), 3,
      sym_field,
      sym_verify_statement,
      aux_sym_entity_block_repeat1,
  [397] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      anon_sym_RBRACE,
    ACTIONS(123), 1,
      aux_sym_annotation_token1,
    ACTIONS(119), 2,
      anon_sym_verify,
      sym_identifier,
    STATE(32), 2,
      sym_annotation,
      aux_sym_field_repeat1,
  [415] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      ts_builtin_sym_end,
    ACTIONS(127), 5,
      anon_sym_use,
      anon_sym_spec,
      anon_sym_ref,
      anon_sym_define,
      sym_identifier,
  [429] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      sym_identifier,
    ACTIONS(132), 1,
      anon_sym_RBRACE,
    ACTIONS(134), 1,
      anon_sym_verify,
    STATE(24), 3,
      sym_field,
      sym_verify_statement,
      aux_sym_entity_block_repeat1,
  [447] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 1,
      ts_builtin_sym_end,
    ACTIONS(139), 5,
      anon_sym_use,
      anon_sym_spec,
      anon_sym_ref,
      anon_sym_define,
      sym_identifier,
  [461] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      ts_builtin_sym_end,
    ACTIONS(143), 5,
      anon_sym_use,
      anon_sym_spec,
      anon_sym_ref,
      anon_sym_define,
      sym_identifier,
  [475] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 1,
      ts_builtin_sym_end,
    ACTIONS(147), 5,
      anon_sym_use,
      anon_sym_spec,
      anon_sym_ref,
      anon_sym_define,
      sym_identifier,
  [489] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(7), 1,
      sym__union_variant,
    STATE(17), 1,
      sym_union_variants,
    ACTIONS(149), 4,
      sym_negative_integer,
      sym_identifier,
      sym_string,
      sym_integer,
  [505] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      ts_builtin_sym_end,
    ACTIONS(153), 5,
      anon_sym_use,
      anon_sym_spec,
      anon_sym_ref,
      anon_sym_define,
      sym_identifier,
  [519] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      sym_identifier,
    ACTIONS(89), 1,
      anon_sym_verify,
    ACTIONS(155), 1,
      anon_sym_RBRACE,
    STATE(24), 3,
      sym_field,
      sym_verify_statement,
      aux_sym_entity_block_repeat1,
  [537] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 1,
      ts_builtin_sym_end,
    ACTIONS(159), 5,
      anon_sym_use,
      anon_sym_spec,
      anon_sym_ref,
      anon_sym_define,
      sym_identifier,
  [551] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      aux_sym_annotation_token1,
    ACTIONS(163), 1,
      anon_sym_RBRACE,
    ACTIONS(161), 2,
      anon_sym_verify,
      sym_identifier,
    STATE(39), 2,
      sym_annotation,
      aux_sym_field_repeat1,
  [569] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      ts_builtin_sym_end,
    ACTIONS(167), 5,
      anon_sym_use,
      anon_sym_spec,
      anon_sym_ref,
      anon_sym_define,
      sym_identifier,
  [583] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      ts_builtin_sym_end,
    ACTIONS(171), 5,
      anon_sym_use,
      anon_sym_spec,
      anon_sym_ref,
      anon_sym_define,
      sym_identifier,
  [597] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      sym_identifier,
    ACTIONS(89), 1,
      anon_sym_verify,
    ACTIONS(173), 1,
      anon_sym_RBRACE,
    STATE(36), 3,
      sym_field,
      sym_verify_statement,
      aux_sym_entity_block_repeat1,
  [615] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      sym_identifier,
    ACTIONS(89), 1,
      anon_sym_verify,
    ACTIONS(175), 1,
      anon_sym_RBRACE,
    STATE(24), 3,
      sym_field,
      sym_verify_statement,
      aux_sym_entity_block_repeat1,
  [633] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      ts_builtin_sym_end,
    ACTIONS(179), 5,
      anon_sym_use,
      anon_sym_spec,
      anon_sym_ref,
      anon_sym_define,
      sym_identifier,
  [647] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 1,
      sym_identifier,
    ACTIONS(185), 1,
      anon_sym_RBRACK,
    STATE(70), 1,
      sym__list_item,
    ACTIONS(183), 3,
      sym_scheme_ref_id,
      sym_string,
      sym_integer,
  [665] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      anon_sym_RBRACE,
    ACTIONS(191), 1,
      aux_sym_annotation_token1,
    ACTIONS(187), 2,
      anon_sym_verify,
      sym_identifier,
    STATE(39), 2,
      sym_annotation,
      aux_sym_field_repeat1,
  [683] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 1,
      sym_identifier,
    ACTIONS(194), 1,
      anon_sym_RBRACK,
    STATE(70), 1,
      sym__list_item,
    ACTIONS(183), 3,
      sym_scheme_ref_id,
      sym_string,
      sym_integer,
  [701] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 1,
      ts_builtin_sym_end,
    ACTIONS(198), 5,
      anon_sym_use,
      anon_sym_spec,
      anon_sym_ref,
      anon_sym_define,
      sym_identifier,
  [715] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      anon_sym_LBRACK_RBRACK,
    ACTIONS(200), 2,
      anon_sym_verify,
      sym_identifier,
    ACTIONS(202), 2,
      anon_sym_RBRACE,
      aux_sym_annotation_token1,
  [730] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(11), 1,
      sym__union_variant,
    ACTIONS(206), 4,
      sym_negative_integer,
      sym_identifier,
      sym_string,
      sym_integer,
  [743] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      sym_string,
    ACTIONS(208), 2,
      anon_sym_verify,
      sym_identifier,
    ACTIONS(210), 2,
      anon_sym_RBRACE,
      aux_sym_annotation_token1,
  [758] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 1,
      sym_identifier,
    STATE(70), 1,
      sym__list_item,
    ACTIONS(183), 3,
      sym_scheme_ref_id,
      sym_string,
      sym_integer,
  [773] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 1,
      sym_identifier,
    ACTIONS(217), 1,
      anon_sym_RBRACE,
    STATE(46), 2,
      sym_field,
      aux_sym_ref_full_repeat1,
  [787] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 2,
      anon_sym_verify,
      sym_identifier,
    ACTIONS(221), 2,
      anon_sym_RBRACE,
      aux_sym_annotation_token1,
  [799] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      sym_identifier,
    ACTIONS(225), 1,
      anon_sym_RBRACE,
    STATE(46), 2,
      sym_field,
      aux_sym_ref_full_repeat1,
  [813] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      sym_identifier,
    ACTIONS(227), 1,
      anon_sym_RBRACE,
    STATE(46), 2,
      sym_field,
      aux_sym_ref_full_repeat1,
  [827] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      sym_identifier,
    ACTIONS(229), 1,
      anon_sym_RBRACE,
    STATE(49), 2,
      sym_field,
      aux_sym_ref_full_repeat1,
  [841] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 2,
      anon_sym_verify,
      sym_identifier,
    ACTIONS(233), 2,
      anon_sym_RBRACE,
      aux_sym_annotation_token1,
  [853] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 2,
      anon_sym_verify,
      sym_identifier,
    ACTIONS(237), 2,
      anon_sym_RBRACE,
      aux_sym_annotation_token1,
  [865] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 2,
      anon_sym_verify,
      sym_identifier,
    ACTIONS(241), 2,
      anon_sym_RBRACE,
      aux_sym_annotation_token1,
  [877] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 2,
      anon_sym_verify,
      sym_identifier,
    ACTIONS(245), 2,
      anon_sym_RBRACE,
      aux_sym_annotation_token1,
  [889] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 2,
      anon_sym_verify,
      sym_identifier,
    ACTIONS(249), 2,
      anon_sym_RBRACE,
      aux_sym_annotation_token1,
  [901] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      sym_identifier,
    ACTIONS(251), 1,
      anon_sym_RBRACE,
    STATE(48), 2,
      sym_field,
      aux_sym_ref_full_repeat1,
  [915] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 2,
      anon_sym_verify,
      sym_identifier,
    ACTIONS(255), 2,
      anon_sym_RBRACE,
      aux_sym_annotation_token1,
  [927] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 2,
      anon_sym_verify,
      sym_identifier,
    ACTIONS(259), 2,
      anon_sym_RBRACE,
      aux_sym_annotation_token1,
  [939] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 2,
      anon_sym_verify,
      sym_identifier,
    ACTIONS(263), 2,
      anon_sym_RBRACE,
      aux_sym_annotation_token1,
  [951] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      anon_sym_RBRACE,
    ACTIONS(265), 2,
      anon_sym_verify,
      sym_identifier,
  [962] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      anon_sym_LBRACE,
    ACTIONS(271), 1,
      anon_sym_EQ,
    ACTIONS(273), 1,
      sym_string,
  [975] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      anon_sym_COMMA,
    ACTIONS(278), 1,
      anon_sym_RBRACE,
    STATE(62), 1,
      aux_sym_selective_import_repeat1,
  [988] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 1,
      anon_sym_COMMA,
    ACTIONS(282), 1,
      anon_sym_RBRACK,
    STATE(65), 1,
      aux_sym_list_repeat1,
  [1001] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(286), 1,
      anon_sym_RBRACE,
    ACTIONS(284), 2,
      anon_sym_verify,
      sym_identifier,
  [1012] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      anon_sym_RBRACK,
    ACTIONS(288), 1,
      anon_sym_COMMA,
    STATE(68), 1,
      aux_sym_list_repeat1,
  [1025] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(290), 1,
      anon_sym_COMMA,
    ACTIONS(292), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      aux_sym_selective_import_repeat1,
  [1038] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(290), 1,
      anon_sym_COMMA,
    ACTIONS(294), 1,
      anon_sym_RBRACE,
    STATE(62), 1,
      aux_sym_selective_import_repeat1,
  [1051] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 1,
      anon_sym_COMMA,
    ACTIONS(299), 1,
      anon_sym_RBRACK,
    STATE(68), 1,
      aux_sym_list_repeat1,
  [1064] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(301), 1,
      sym_identifier,
    ACTIONS(303), 1,
      sym_string,
  [1074] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1082] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1090] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(305), 1,
      sym_identifier,
  [1097] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(307), 1,
      sym_identifier,
  [1104] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(309), 1,
      ts_builtin_sym_end,
  [1111] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 1,
      anon_sym_LBRACE,
  [1118] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 1,
      sym_string,
  [1125] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(315), 1,
      sym_import_path,
  [1132] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(317), 1,
      anon_sym_LBRACE,
  [1139] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 1,
      sym_string,
  [1146] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(321), 1,
      sym_scheme_ref_id,
  [1153] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 1,
      anon_sym_RBRACK,
  [1160] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(323), 1,
      sym_identifier,
  [1167] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 1,
      anon_sym_LBRACE,
  [1174] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(327), 1,
      sym_identifier,
  [1181] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 1,
      sym_string,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 36,
  [SMALL_STATE(4)] = 72,
  [SMALL_STATE(5)] = 104,
  [SMALL_STATE(6)] = 124,
  [SMALL_STATE(7)] = 144,
  [SMALL_STATE(8)] = 164,
  [SMALL_STATE(9)] = 184,
  [SMALL_STATE(10)] = 201,
  [SMALL_STATE(11)] = 222,
  [SMALL_STATE(12)] = 237,
  [SMALL_STATE(13)] = 255,
  [SMALL_STATE(14)] = 269,
  [SMALL_STATE(15)] = 287,
  [SMALL_STATE(16)] = 301,
  [SMALL_STATE(17)] = 319,
  [SMALL_STATE(18)] = 333,
  [SMALL_STATE(19)] = 347,
  [SMALL_STATE(20)] = 365,
  [SMALL_STATE(21)] = 379,
  [SMALL_STATE(22)] = 397,
  [SMALL_STATE(23)] = 415,
  [SMALL_STATE(24)] = 429,
  [SMALL_STATE(25)] = 447,
  [SMALL_STATE(26)] = 461,
  [SMALL_STATE(27)] = 475,
  [SMALL_STATE(28)] = 489,
  [SMALL_STATE(29)] = 505,
  [SMALL_STATE(30)] = 519,
  [SMALL_STATE(31)] = 537,
  [SMALL_STATE(32)] = 551,
  [SMALL_STATE(33)] = 569,
  [SMALL_STATE(34)] = 583,
  [SMALL_STATE(35)] = 597,
  [SMALL_STATE(36)] = 615,
  [SMALL_STATE(37)] = 633,
  [SMALL_STATE(38)] = 647,
  [SMALL_STATE(39)] = 665,
  [SMALL_STATE(40)] = 683,
  [SMALL_STATE(41)] = 701,
  [SMALL_STATE(42)] = 715,
  [SMALL_STATE(43)] = 730,
  [SMALL_STATE(44)] = 743,
  [SMALL_STATE(45)] = 758,
  [SMALL_STATE(46)] = 773,
  [SMALL_STATE(47)] = 787,
  [SMALL_STATE(48)] = 799,
  [SMALL_STATE(49)] = 813,
  [SMALL_STATE(50)] = 827,
  [SMALL_STATE(51)] = 841,
  [SMALL_STATE(52)] = 853,
  [SMALL_STATE(53)] = 865,
  [SMALL_STATE(54)] = 877,
  [SMALL_STATE(55)] = 889,
  [SMALL_STATE(56)] = 901,
  [SMALL_STATE(57)] = 915,
  [SMALL_STATE(58)] = 927,
  [SMALL_STATE(59)] = 939,
  [SMALL_STATE(60)] = 951,
  [SMALL_STATE(61)] = 962,
  [SMALL_STATE(62)] = 975,
  [SMALL_STATE(63)] = 988,
  [SMALL_STATE(64)] = 1001,
  [SMALL_STATE(65)] = 1012,
  [SMALL_STATE(66)] = 1025,
  [SMALL_STATE(67)] = 1038,
  [SMALL_STATE(68)] = 1051,
  [SMALL_STATE(69)] = 1064,
  [SMALL_STATE(70)] = 1074,
  [SMALL_STATE(71)] = 1082,
  [SMALL_STATE(72)] = 1090,
  [SMALL_STATE(73)] = 1097,
  [SMALL_STATE(74)] = 1104,
  [SMALL_STATE(75)] = 1111,
  [SMALL_STATE(76)] = 1118,
  [SMALL_STATE(77)] = 1125,
  [SMALL_STATE(78)] = 1132,
  [SMALL_STATE(79)] = 1139,
  [SMALL_STATE(80)] = 1146,
  [SMALL_STATE(81)] = 1153,
  [SMALL_STATE(82)] = 1160,
  [SMALL_STATE(83)] = 1167,
  [SMALL_STATE(84)] = 1174,
  [SMALL_STATE(85)] = 1181,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_use_import, 2, 0, 1),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_use_import, 2, 0, 1),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_union_variants_repeat1, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_union_variants_repeat1, 2, 0, 0),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_union_variants_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_variants, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_union_variants, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_variants, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_union_variants, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ref_inline, 3, 0, 3),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ref_inline, 3, 0, 3),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_define_block, 4, 0, 4),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_define_block, 4, 0, 4),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_block, 4, 0, 5),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entity_block, 4, 0, 5),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_block, 4, 0, 6),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_union_block, 4, 0, 6),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_use_import, 3, 0, 2),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_use_import, 3, 0, 2),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selective_import, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_selective_import, 3, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field, 2, 0, 8),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 2, 0, 8),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_spec_block, 5, 0, 4),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_spec_block, 5, 0, 4),
  [129] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_entity_block_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_entity_block_repeat1, 2, 0, 0),
  [134] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_entity_block_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ref_full, 5, 0, 3),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ref_full, 5, 0, 3),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_define_block, 5, 0, 4),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_define_block, 5, 0, 4),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ref_block, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ref_block, 1, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_block, 5, 0, 9),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entity_block, 5, 0, 9),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selective_import, 4, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_selective_import, 4, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field, 3, 0, 8),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 3, 0, 8),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ref_full, 6, 0, 3),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ref_full, 6, 0, 3),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_spec_block, 4, 0, 4),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_spec_block, 4, 0, 4),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_block, 6, 0, 9),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entity_block, 6, 0, 9),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_field_repeat1, 2, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_field_repeat1, 2, 0, 0),
  [191] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_field_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entity_block, 5, 0, 5),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_entity_block, 5, 0, 5),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__value, 1, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 1, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_annotation, 1, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotation, 1, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [214] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ref_full_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_ref_full_repeat1, 2, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 5, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 5, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [231] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_nested_block, 2, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nested_block, 2, 0, 0),
  [239] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_type, 2, 0, 11),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_type, 2, 0, 11),
  [243] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_nested_block, 3, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nested_block, 3, 0, 0),
  [247] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 4, 0, 0),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4, 0, 0),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [253] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_annotation, 2, 0, 0),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotation, 2, 0, 0),
  [257] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3, 0, 0),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 0),
  [261] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [265] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_verify_statement, 3, 0, 10),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verify_statement, 3, 0, 10),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [275] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_selective_import_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_selective_import_repeat1, 2, 0, 0),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [284] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_verify_statement, 2, 0, 7),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_verify_statement, 2, 0, 7),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [296] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [309] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_specforge(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "specforge",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
