[package]
name = "specforge-lsp"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
autotests = false

[[test]]
name = "tests"
path = "tests/main.rs"

[dependencies]
specforge-diagnostics = { path = "../specforge-diagnostics" }
specforge-common = { workspace = true }
specforge-emitter = { path = "../specforge-emitter" }
specforge-formatter = { workspace = true }
specforge-graph = { path = "../specforge-graph" }
specforge-ops = { path = "../specforge-ops" }
specforge-parser = { workspace = true }
specforge-project = { path = "../specforge-project" }
specforge-registry = { path = "../specforge-registry" }
specforge-resolver = { path = "../specforge-resolver" }
specforge-watch = { path = "../specforge-watch", features = ["tokio"] }
tree-sitter = { workspace = true }
tower-lsp = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
specforge-component = { path = "../specforge-component" }
specforge-installed = { path = "../specforge-installed", features = ["testing"] }
specforge-extension-sdk = { path = "../specforge-extension-sdk" }
specforge-wasm = { path = "../specforge-wasm", features = ["testing"] }
specforge-test = { workspace = true }
specforge-test-macros = { workspace = true }
tempfile = { workspace = true }
tree-sitter-specforge = { workspace = true }
