[package]
name = "specforge-registry-client"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
autotests = false

[[test]]
name = "tests"
path = "tests/main.rs"

[dependencies]
specforge-common = { workspace = true }
specforge-protocol-types = { path = "../specforge-protocol-types" }
specforge-registry-wire = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
semver = { workspace = true }
sha2 = { workspace = true }
reqwest = { workspace = true }
httpdate = "1"
keyring = "3"
ed25519-dalek = "2.2.0"
getrandom = "0.3"
hex = "0.4.3"
chrono = "0.4.41"

[dev-dependencies]
parking_lot = "0.12"
tempfile = { workspace = true }
