mod brief;
mod budget;
mod context;
mod diagnostic_fmt;
mod dot;
mod json;
mod plan;
mod query;
mod scope;
mod stats;
mod trace;

pub use brief::emit_brief;
pub use diagnostic_fmt::{format_diagnostic, serialize_diagnostics};
pub use budget::{emit_json_with_budget, emit_json_with_budget_strategy};
pub use context::emit_context;
pub use dot::emit_dot;
pub use json::{emit_json, emit_json as emit_graph};
pub use plan::{serialize_plan_result, validate_plan, PlanValidationResult};
pub use query::query;
pub use scope::{emit_context_scoped, emit_json_scoped};
pub use stats::{compute_stats, compute_stats_with_diagnostics, compute_stats_with_testable, ProjectStats};
pub use trace::{detect_trace_gaps, serialize_trace, serialize_trace_all, trace, trace_all, TraceChain, TraceLink};
