[package]
name = "specforge-component"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
specforge-wasm = { path = "../specforge-wasm" }
specforge-common = { workspace = true }
wasmtime = { version = "49", features = ["component-model", "cache"] }
wasmtime-wasi = "49"
wit-bindgen = "0.30"

[dev-dependencies]
tempfile = { workspace = true }
wat = "=1.258.0"
serde_json = { workspace = true }
specforge-test = { workspace = true }
specforge-test-macros = { workspace = true }

[[test]]
name = "caught_signals"
harness = false
