//! @specforge/formal — the formal-methods builtin, now authored with the
//! SpecForge extension SDK (SDK adoption; spec/extension-sdk docs).
//!
//! The describe payloads are the protocol envelopes extracted from the
//! in-process builtin (`crates/specforge-emitter/src/builtins/formal.rs`,
//! regenerated by `xtask extract-extension-json`). They are served through
//! the SDK's `raw_category` escape hatch, and the handshake is derived by the
//! SDK from the extension metadata — contribution flags included.

use specforge_extension_sdk::prelude::*;
use specforge_extension_sdk::{PassDiagnostic, PassEntity, PassInput};

static DESCRIBE_ENTITIES: &[u8] = include_bytes!("describe_entities.json");
static DESCRIBE_EDGES: &[u8] = include_bytes!("describe_edges.json");
static DESCRIBE_FIELDS: &[u8] = include_bytes!("describe_fields.json");
static DESCRIBE_SHARED_FIELDS: &[u8] = include_bytes!("describe_shared_fields.json");
static DESCRIBE_ENHANCEMENTS: &[u8] = include_bytes!("describe_enhancements.json");
static DESCRIBE_VALIDATION_RULES: &[u8] = include_bytes!("describe_validation_rules.json");
static DESCRIBE_SURFACES: &[u8] = include_bytes!("describe_surfaces.json");
static DESCRIBE_FEATURE_FLAGS: &[u8] = include_bytes!("describe_feature_flags.json");

#[specforge_extension_sdk::extension(name = "@specforge/formal", version = "1.0.0")]
struct Formal;

impl Contributions for Formal {
    fn contribute(c: &mut ContributionsBuilder) {
        c.meta.peer_dependencies.push(PeerDependency {
            name: "@specforge/software".to_string(),
            version: "^1.0".to_string(),
            optional: false,
        });

        // Declaration order is deliberately shuffled; the host must order
        // passes by the declared after-constraints, not by declaration.
        c.pass("event_graph_analyze", |p| {
            p.after("layering_verify");
        });
        c.pass("coverage_tracking", |p| {
            p.after("event_graph_analyze");
        });
        c.pass("condition_check", |p| {
            p.after("resolve");
        });
        c.pass("layering_verify", |p| {
            p.after("condition_check");
        });

        for (category, bytes) in [
            ("entities", DESCRIBE_ENTITIES),
            ("edges", DESCRIBE_EDGES),
            ("fields", DESCRIBE_FIELDS),
            ("shared_fields", DESCRIBE_SHARED_FIELDS),
            ("enhancements", DESCRIBE_ENHANCEMENTS),
            ("validation_rules", DESCRIBE_VALIDATION_RULES),
            ("surfaces", DESCRIBE_SURFACES),
            ("feature_flags", DESCRIBE_FEATURE_FLAGS),
        ] {
            let envelope: serde_json::Value = serde_json::from_slice(bytes)
                .unwrap_or_else(|e| panic!("formal describe '{category}' is not valid JSON: {e}"));
            c.raw_category(category, envelope["items"].clone());
        }
    }
}

// ── Extension-owned compiler passes ────────────────────────────────────────
// Wire ABI (v1): `__pass_<name>` receives { "entities": [...] } (the host's
// ValidationEntity shape) and returns an array of host Diagnostic objects.
// The SDK's #[compiler_pass] attribute generates the export.

/// condition_check (Meyer's Design by Contract, RES-25 part I): a behavior
/// that obligates its callers (requires) must provide a benefit (ensures).
#[specforge_extension_sdk::compiler_pass(name = "condition_check", after = "resolve")]
fn pass_condition_check(input: &PassInput) -> Vec<PassDiagnostic> {
    let mut findings = Vec::new();
    for entity in &input.entities {
        if entity.kind != "behavior" {
            continue;
        }
        let has_requires = non_empty(entity, "requires");
        let has_ensures = non_empty(entity, "ensures");
        if has_requires && !has_ensures {
            findings.push(
                PassDiagnostic::warning(
                    "W096",
                    format!("behavior '{}' declares requires but no ensures", entity.id),
                )
                .with_suggestion(
                    "add an ensures clause: a caller's obligation must buy a guarantee",
                ),
            );
        }
    }
    findings
}

/// coverage_tracking (RES-25 part I, W035): one aggregated warning per run
/// listing the coverage items (invariants and testable entities) that carry
/// no `tests` linkage - the undischarged set of the discharge funnel.
#[specforge_extension_sdk::compiler_pass(name = "coverage_tracking", after = "event_graph_analyze")]
fn pass_coverage_tracking(input: &PassInput) -> Vec<PassDiagnostic> {
    let undischarged: Vec<&str> = input
        .entities
        .iter()
        .filter(|e| {
            let is_item = e.kind == "invariant" || e.testable;
            let linked = e
                .fields
                .iter()
                .any(|(k, v)| k == "tests" && !v.trim().is_empty());
            is_item && !linked
        })
        .map(|e| e.id.as_str())
        .collect();

    if undischarged.is_empty() {
        return Vec::new();
    }

    const PREVIEW: usize = 10;
    let listed: Vec<&str> = undischarged.iter().take(PREVIEW).copied().collect();
    let rest = undischarged.len().saturating_sub(PREVIEW);
    let mut message = format!(
        "{} coverage item(s) are not covered by a test linkage",
        undischarged.len()
    );
    message.push_str(&format!(": {}", listed.join(", ")));
    if rest > 0 {
        message.push_str(&format!(" … and {rest} more"));
    }

    vec![PassDiagnostic::warning("W035", message)
        .with_suggestion("add a `tests [...]` field pointing at the executable tests")]
}

fn non_empty(entity: &PassEntity, field: &str) -> bool {
    entity
        .fields
        .get(field)
        .is_some_and(|v| !v.trim().is_empty())
}

/// layering_verify (RES-25 part I): refinement chains must stay acyclic
/// (E041) and shallow (W031 beyond depth 4), keep the abstract's ensures
/// (E031), and every abstract behavior needs a refinement (W030).
const MAX_LAYERING_DEPTH: usize = 4;
const BEHAVIOR_KIND: &str = "behavior";
const REFINEMENT_KIND: &str = "refinement";
// Graph edges are labelled with the field that declared them, not the
// describe_fields edge-type name (see specforge-resolver linker).
const REFINEMENT_CONCRETE_FIELD: &str = "concrete_entity";
const REFINEMENT_ABSTRACT_FIELD: &str = "abstract_entity";
const REFINES_FIELD: &str = "refines";
const ABSTRACT_FLAG_FIELD: &str = "abstract";

/// How a concrete -> abstract layering step was declared.
#[derive(Debug, Clone, Copy, PartialEq)]
enum Declared<'a> {
    /// A `refinement` entity naming both behaviors.
    Entity(&'a str),
    /// A `refines` field on the concrete behavior.
    Field,
}

#[derive(Debug, Clone, Copy)]
struct LayeringStep<'a> {
    declared: Declared<'a>,
    concrete: &'a str,
    abstract_id: &'a str,
}

/// Every concrete -> abstract step, from `refinement` entities and from
/// `refines` fields on behaviors. When both declare the same pair the
/// refinement entity wins (it is the more explicit record). Sorted by pair.
fn layering_steps(input: &PassInput) -> Vec<LayeringStep<'_>> {
    use std::collections::{BTreeMap, HashMap};

    let kind_of: HashMap<&str, &str> = input
        .entities
        .iter()
        .map(|e| (e.id.as_str(), e.kind.as_str()))
        .collect();
    let mut concrete: BTreeMap<&str, &str> = BTreeMap::new();
    let mut abstract_of: BTreeMap<&str, &str> = BTreeMap::new();
    let mut steps: BTreeMap<(&str, &str), Declared> = BTreeMap::new();
    for edge in &input.edges {
        let (source, target) = (edge.source.as_str(), edge.target.as_str());
        match (kind_of.get(source).copied(), edge.label.as_str()) {
            (Some(REFINEMENT_KIND), REFINEMENT_CONCRETE_FIELD) => {
                concrete.insert(source, target);
            }
            (Some(REFINEMENT_KIND), REFINEMENT_ABSTRACT_FIELD) => {
                abstract_of.insert(source, target);
            }
            (Some(BEHAVIOR_KIND), REFINES_FIELD) => {
                steps.entry((source, target)).or_insert(Declared::Field);
            }
            _ => {}
        }
    }
    for (refinement, concrete) in concrete {
        if let Some(&abstract_id) = abstract_of.get(refinement) {
            steps
                .entry((concrete, abstract_id))
                .and_modify(|declared| {
                    if *declared == Declared::Field {
                        *declared = Declared::Entity(refinement);
                    }
                })
                .or_insert(Declared::Entity(refinement));
        }
    }
    steps
        .into_iter()
        .map(|((concrete, abstract_id), declared)| LayeringStep {
            declared,
            concrete,
            abstract_id,
        })
        .collect()
}

#[specforge_extension_sdk::compiler_pass(name = "layering_verify", after = "condition_check")]
fn pass_layering_verify(input: &PassInput) -> Vec<PassDiagnostic> {
    use std::collections::{HashMap, HashSet};

    let by_id: HashMap<&str, &PassEntity> =
        input.entities.iter().map(|e| (e.id.as_str(), e)).collect();
    let is_abstract = |id: &str| {
        by_id
            .get(id)
            .and_then(|e| e.fields.get(ABSTRACT_FLAG_FIELD))
            .is_some_and(|v| v == "true")
    };
    let steps = layering_steps(input);
    // concrete behavior -> the abstract behaviors it refines
    let mut refines: HashMap<&str, Vec<&str>> = HashMap::new();
    for step in &steps {
        if by_id.contains_key(step.concrete) && by_id.contains_key(step.abstract_id) {
            refines
                .entry(step.concrete)
                .or_default()
                .push(step.abstract_id);
        }
    }

    let mut findings = Vec::new();
    // Cycle detection over the refinement DAG (E041).
    let mut state: HashMap<&str, u8> = HashMap::new(); // 0 = visiting, 1 = done
    fn visit<'a>(
        id: &'a str,
        refines: &HashMap<&'a str, Vec<&'a str>>,
        state: &mut HashMap<&'a str, u8>,
        findings: &mut Vec<PassDiagnostic>,
    ) {
        match state.get(id) {
            Some(1) => return,
            Some(0) => {
                findings.push(PassDiagnostic::new(
                    "E041",
                    PassSeverity::Error,
                    format!("refinement chain cycle through '{}'", id),
                ));
                return;
            }
            _ => {}
        }
        state.insert(id, 0);
        if let Some(targets) = refines.get(id) {
            for target in targets.clone() {
                visit(target, refines, state, findings);
            }
        }
        state.insert(id, 1);
    }
    for id in refines.keys().copied().collect::<Vec<_>>() {
        visit(id, &refines, &mut state, &mut findings);
    }

    // Depth accounting (W031): chain depth beyond MAX_LAYERING_DEPTH. Walks
    // that revisit a node are cycles — already reported as E041, so they are
    // skipped here rather than double-reported as depth violations.
    let mut depth: HashMap<&str, usize> = HashMap::new();
    for id in refines.keys() {
        let mut current = *id;
        let mut steps = 0usize;
        let mut walked: HashMap<&str, ()> = HashMap::new();
        let mut cyclic = false;
        loop {
            if walked.insert(current, ()).is_some() {
                cyclic = true;
                break;
            }
            match refines.get(current).and_then(|t| t.first()) {
                Some(&next) if !depth.contains_key(&next) => {
                    current = next;
                    steps += 1;
                    if steps > MAX_LAYERING_DEPTH {
                        break;
                    }
                }
                Some(&next) => {
                    steps += depth[&next] + 1;
                    break;
                }
                None => break,
            }
        }
        if !cyclic {
            depth.insert(id, steps);
        }
    }
    for (id, d) in &depth {
        if *d > MAX_LAYERING_DEPTH {
            let message = if let Some(e) = by_id.get(id) {
                format!(
                    "behavior '{}' sits in a refinement chain {} layers deep (max {})",
                    e.id, d, MAX_LAYERING_DEPTH
                )
            } else {
                continue;
            };
            findings.push(PassDiagnostic::warning("W031", message).with_suggestion(
                "split the refinement chain or collapse intermediate abstractions",
            ));
        }
    }
    // E031 (C10-02): named-condition set inclusion. For each concrete
    // entity refining an abstract one, the concrete ensures names must be a
    // superset of the abstract's (pattern-catalog fa_pattern_e031):
    // strengthening is allowed, weakening is the layering violation.
    let ensures_names = |id: &str| -> Option<Vec<String>> {
        let entity = by_id.get(id)?;
        let raw = entity.fields.get("ensures")?;
        let names: Vec<String> = raw
            .split(',')
            .map(|s| s.trim().to_string())
            .filter(|s| !s.is_empty())
            .collect();
        if names.is_empty() {
            None
        } else {
            Some(names)
        }
    };
    for step in &steps {
        let LayeringStep {
            declared,
            concrete,
            abstract_id,
        } = *step;
        let (Some(concrete_names), Some(abstract_names)) =
            (ensures_names(concrete), ensures_names(abstract_id))
        else {
            continue;
        };
        let missing: Vec<&str> = abstract_names
            .iter()
            .filter(|name| !concrete_names.contains(name))
            .map(String::as_str)
            .collect();
        if !missing.is_empty() {
            let names_list = missing.join(", ");
            let message = match declared {
                Declared::Entity(refinement) => format!(
                    "refinement '{refinement}': '{concrete}' drops ensures condition(s) [{names_list}] from abstract '{abstract_id}'"
                ),
                Declared::Field => format!(
                    "'{concrete}' refines '{abstract_id}' but drops its ensures condition(s) [{names_list}]"
                ),
            };
            findings.push(PassDiagnostic::new("E031", PassSeverity::Error, message).with_suggestion(
                "keep every abstract ensures condition in the refinement (strengthening is allowed; weakening is not)",
            ));
        }
    }

    // W110: the `refines` field declares layering against an abstraction,
    // so its target must be marked `abstract true`. Refinement entities
    // predate the flag and may name any behavior.
    for step in steps.iter().filter(|s| s.declared == Declared::Field) {
        if by_id.contains_key(step.abstract_id) && !is_abstract(step.abstract_id) {
            findings.push(
                PassDiagnostic::warning(
                    "W110",
                    format!(
                        "'{}' refines '{}', which is not marked `abstract true`",
                        step.concrete, step.abstract_id
                    ),
                )
                .with_suggestion(format!(
                    "add `abstract true` to '{}', or refine an abstract behavior",
                    step.abstract_id
                )),
            );
        }
    }

    // W030: an abstract behavior nothing refines is an incomplete layer.
    let refined: HashSet<&str> = steps.iter().map(|s| s.abstract_id).collect();
    for entity in input.entities.iter().filter(|e| {
        e.kind == BEHAVIOR_KIND && is_abstract(&e.id) && !refined.contains(e.id.as_str())
    }) {
        findings.push(
            PassDiagnostic::warning(
                "W030",
                format!("abstract behavior '{}' has no concrete refinement", entity.id),
            )
            .with_suggestion(format!(
                "add a behavior with `refines {}`, or a `refinement` entity naming it as abstract_entity",
                entity.id
            )),
        );
    }

    // Deterministic order: DFS seeds came from a HashMap, so sort by
    // (entity, code) before returning (hardening-plan D4 / R-6).
    findings.sort_by(|a, b| a.code.cmp(&b.code).then_with(|| a.message.cmp(&b.message)));
    // Two refinements naming the same concrete/abstract pair make the DFS
    // revisit the same back edge — dedup identical diagnostics (C10-11).
    findings.dedup_by(|a, b| a.code == b.code && a.message == b.message);
    findings
}

/// event_graph_analyze (RES-25 part I): every produced event should have a
/// consumer (W029).
#[specforge_extension_sdk::compiler_pass(name = "event_graph_analyze", after = "layering_verify")]
fn pass_event_graph_analyze(input: &PassInput) -> Vec<PassDiagnostic> {
    use std::collections::HashMap;

    let by_id: HashMap<&str, &PassEntity> =
        input.entities.iter().map(|e| (e.id.as_str(), e)).collect();
    let mut produced: HashMap<&str, usize> = HashMap::new();
    let mut consumed: HashMap<&str, usize> = HashMap::new();
    for edge in &input.edges {
        match edge.label.as_str() {
            "produces" => *produced.entry(edge.target.as_str()).or_default() += 1,
            "consumes" => *consumed.entry(edge.target.as_str()).or_default() += 1,
            _ => {}
        }
    }

    let mut findings: Vec<PassDiagnostic> = Vec::new();
    // Process semantics (C10-00): an event participating in a process is
    // used by it (suppresses W029), and ProcessComposesProcess edges form a
    // composition graph whose cycles are the documented E042.
    let mut process_edges: std::collections::BTreeMap<&str, std::collections::BTreeSet<&str>> =
        std::collections::BTreeMap::new();
    for edge in &input.edges {
        // The graph labels these edges with the FIELD name (sub_processes /
        // processes); the edge-type names (ProcessComposesProcess /
        // EventParticipatesInProcess) match when hosts send type labels.
        match edge.label.as_str() {
            "EventParticipatesInProcess" | "processes" => {
                *consumed.entry(edge.source.as_str()).or_default() += 1;
            }
            "ProcessComposesProcess" | "sub_processes" => {
                process_edges
                    .entry(edge.source.as_str())
                    .or_default()
                    .insert(edge.target.as_str());
            }
            _ => {}
        }
    }

    // Process composition cycles (E042): exact-membership DFS over the
    // composition graph, deterministic order (sorted seeds + sorted edges).
    {
        let mut seeds: Vec<&str> = process_edges.keys().copied().collect();
        seeds.sort();
        let mut color: HashMap<&str, u8> = process_edges.keys().map(|&k| (k, 0u8)).collect();
        let mut path: Vec<&str> = Vec::new();
        fn dfs<'a>(
            node: &'a str,
            adj: &std::collections::BTreeMap<&'a str, std::collections::BTreeSet<&'a str>>,
            color: &mut HashMap<&'a str, u8>,
            path: &mut Vec<&'a str>,
            by_id: &HashMap<&'a str, &'a PassEntity>,
            findings: &mut Vec<PassDiagnostic>,
        ) {
            color.insert(node, 1);
            path.push(node);
            if let Some(neighbors) = adj.get(node) {
                for &next in neighbors {
                    match color.get(next).copied().unwrap_or(0) {
                        1 => {
                            if let Some(pos) = path.iter().position(|&n| n == next) {
                                let cycle: Vec<&str> = path[pos..].to_vec();
                                let rendered = cycle.join(" -> ");
                                let first = by_id.get(cycle[0]).copied();
                                findings.push(
                                    PassDiagnostic::new(
                                        "E042",
                                        PassSeverity::Error,
                                        format!(
                                            "process composition cycle: {rendered} -> {next}"
                                        ),
                                    )
                                    .with_span(PassSpan {
                                        file: first
                                            .and_then(|e| e.span.as_ref())
                                            .map(|s| s.file.clone())
                                            .unwrap_or_default(),
                                        start_line: first
                                            .and_then(|e| e.span.as_ref())
                                            .map(|s| s.start_line)
                                            .unwrap_or(0),
                                        start_col: first
                                            .and_then(|e| e.span.as_ref())
                                            .map(|s| s.start_col)
                                            .unwrap_or(0),
                                        end_line: first
                                            .and_then(|e| e.span.as_ref())
                                            .map(|s| s.end_line)
                                            .unwrap_or(0),
                                        end_col: first
                                            .and_then(|e| e.span.as_ref())
                                            .map(|s| s.end_col)
                                            .unwrap_or(0),
                                    })
                                    .with_suggestion(
                                        "break the composition cycle — a process cannot compose (transitively) with itself",
                                    ),
                                );
                            }
                        }
                        0 => dfs(next, adj, color, path, by_id, findings),
                        _ => {}
                    }
                }
            }
            path.pop();
            color.insert(node, 2);
        }
        for &seed in &seeds {
            if color.get(&seed).copied() == Some(0) {
                dfs(
                    seed,
                    &process_edges,
                    &mut color,
                    &mut path,
                    &by_id,
                    &mut findings,
                );
            }
        }
    }

    for (id, producers) in &produced {
        if consumed.contains_key(id) {
            continue;
        }
        let Some(entity) = by_id.get(id) else {
            continue;
        };
        if entity.kind != "event" {
            continue;
        }
        findings.push(
            PassDiagnostic::warning(
                "W029",
                format!(
                    "event '{}' is produced ({}x) but never consumed",
                    id, producers
                ),
            )
            .with_span(PassSpan {
                file: entity
                    .span
                    .as_ref()
                    .map(|s| s.file.clone())
                    .unwrap_or_default(),
                start_line: entity.span.as_ref().map(|s| s.start_line).unwrap_or(0),
                start_col: entity.span.as_ref().map(|s| s.start_col).unwrap_or(0),
                end_line: entity.span.as_ref().map(|s| s.end_line).unwrap_or(0),
                end_col: entity.span.as_ref().map(|s| s.end_col).unwrap_or(0),
            })
            .with_suggestion(
                "add a behavior that consumes the event, or drop the produces reference",
            ),
        );
    }
    // Deterministic order: produced-events came from a HashMap (hardening-plan
    // D4 / R-6).
    findings.sort_by(|a, b| a.code.cmp(&b.code).then_with(|| a.message.cmp(&b.message)));
    findings
}

#[cfg(test)]
mod pass_tests {
    use super::*;
    use specforge_extension_sdk::{PassEdge, PassSeverity};

    fn entity(id: &str, kind: &str) -> PassEntity {
        PassEntity {
            id: id.to_string(),
            kind: kind.to_string(),
            fields: std::collections::BTreeMap::new(),
            incoming_edge_count: 0,
            outgoing_edge_count: 0,
            span: None,
            testable: false,
            ..Default::default()
        }
    }

    fn edge(source: &str, target: &str, label: &str) -> PassEdge {
        PassEdge {
            source: source.to_string(),
            target: target.to_string(),
            label: label.to_string(),
        }
    }

    fn codes(findings: &[PassDiagnostic]) -> Vec<&str> {
        findings.iter().map(|f| f.code.as_str()).collect()
    }

    /// The two edges a `refinement` entity's `concrete_entity` /
    /// `abstract_entity` fields produce in the real graph.
    fn refinement(id: &str, concrete: &str, abstract_id: &str) -> [PassEdge; 2] {
        [
            edge(id, concrete, REFINEMENT_CONCRETE_FIELD),
            edge(id, abstract_id, REFINEMENT_ABSTRACT_FIELD),
        ]
    }

    // C10-02: E031 — refinement ensures set inclusion.
    #[test]
    fn e031_subset_refinement_fires_and_superset_passes() {
        let mut abstract_entity = entity("abstract", "behavior");
        abstract_entity.fields.insert(
            "ensures".to_string(),
            "config_created, file_created".to_string(),
        );
        let mut good = entity("good_impl", "behavior");
        good.fields.insert(
            "ensures".to_string(),
            "file_created, config_created, extra_guarantee".to_string(),
        );
        let mut bad = entity("bad_impl", "behavior");
        bad.fields
            .insert("ensures".to_string(), "config_created".to_string());

        let entities = vec![
            abstract_entity,
            good,
            bad,
            entity("r_good", "refinement"),
            entity("r_bad", "refinement"),
        ];
        let edges = [
            refinement("r_good", "good_impl", "abstract"),
            refinement("r_bad", "bad_impl", "abstract"),
        ]
        .concat();
        let findings = pass_layering_verify(&PassInput {
            entities,
            edges,
            ..Default::default()
        });

        assert_eq!(
            codes(&findings),
            vec!["E031"],
            "only the weakening refinement fires: {findings:?}"
        );
        let e031 = &findings[0];
        assert!(
            e031.message.contains("file_created")
                && e031.message.contains("bad_impl")
                && e031.message.contains("r_bad"),
            "message names the refinement, the concrete, and the dropped condition: {}",
            e031.message
        );
        assert!(
            !e031.message.contains("good_impl"),
            "superset refinement must pass: {}",
            e031.message
        );
    }

    // C10-12: describe_validation_rules.json is the single source for the
    // formal rules. The declarative JSON must stay loadable and its
    // one_of/matches constraints must survive the same parse-time
    // validation the engine applies — otherwise a hand edit can silently
    // register a rule that can never fire (or none at all).
    #[test]
    fn describe_validation_rules_are_loadable_and_complete() {
        let raw = String::from_utf8(DESCRIBE_VALIDATION_RULES.to_vec())
            .expect("validation rules describe is UTF-8");
        let doc: serde_json::Value = serde_json::from_str(&raw).expect("valid JSON");
        let items = doc["items"].as_array().expect("items array");

        let codes: Vec<&str> = items.iter().filter_map(|r| r["code"].as_str()).collect();
        for expected in ["W125", "W123", "W126", "W128", "W131", "W134"] {
            assert!(
                codes.contains(&expected),
                "formal rule {expected} missing from describe_validation_rules.json: {codes:?}"
            );
        }

        // Declarative sanity per rule: field_value_constraint rules carry a
        // non-empty constraint; matches patterns are compilable regexes.
        for rule in items {
            let code = rule["code"].as_str().unwrap_or("?");
            if rule["check"].as_str() == Some("field_value_constraint") {
                let constraint = &rule["constraint"];
                assert!(
                    constraint.is_object() && constraint.get("kind").is_some(),
                    "{code}: field_value_constraint without a constraint kind"
                );
                if constraint["kind"].as_str() == Some("matches") {
                    let pattern = constraint["pattern"].as_str().expect("matches pattern");
                    regex::Regex::new(pattern)
                        .unwrap_or_else(|e| panic!("{code}: malformed regex '{pattern}': {e}"));
                }
                if constraint["kind"].as_str() == Some("one_of") {
                    let values = constraint["values"].as_array().expect("one_of values");
                    assert!(!values.is_empty(), "{code}: one_of with empty values");
                }
            }
        }
    }

    #[test]
    fn layering_detects_refinement_cycles() {
        let input = PassInput {
            entities: vec![
                entity("a", "behavior"),
                entity("b", "behavior"),
                entity("c", "behavior"),
                entity("r1", "refinement"),
                entity("r2", "refinement"),
                entity("r3", "refinement"),
            ],
            edges: [
                refinement("r1", "a", "b"),
                refinement("r2", "b", "c"),
                refinement("r3", "c", "a"),
            ]
            .concat(),
            ..Default::default()
        };
        let findings = pass_layering_verify(&input);
        assert_eq!(codes(&findings), vec!["E041"]);
        assert!(matches!(findings[0].severity, PassSeverity::Error));
    }

    #[test]
    fn layering_flags_deep_chains() {
        let mut entities: Vec<PassEntity> = (0..=5)
            .map(|l| entity(&format!("l{l}"), "behavior"))
            .collect();
        let mut edges = Vec::new();
        for w in 0..5 {
            entities.push(entity(&format!("r{w}"), "refinement"));
            edges.extend(refinement(
                &format!("r{w}"),
                &format!("l{w}"),
                &format!("l{}", w + 1),
            ));
        }
        let input = PassInput {
            entities,
            edges,
            ..Default::default()
        };
        let findings = pass_layering_verify(&input);
        assert_eq!(
            codes(&findings),
            vec!["W031"],
            "depth-5 chain: {:?}",
            findings
        );
        assert!(matches!(findings[0].severity, PassSeverity::Warning));
    }

    #[test]
    fn layering_accepts_shallow_acyclic_chains() {
        let input = PassInput {
            entities: vec![
                entity("a", "behavior"),
                entity("b", "behavior"),
                entity("r", "refinement"),
            ],
            edges: refinement("r", "a", "b").to_vec(),
            ..Default::default()
        };
        assert!(pass_layering_verify(&input).is_empty());
    }

    /// Labels no declared field produces (the pre-fix markers) must not be
    /// mistaken for refinements, nor may a `refines` edge from a non-behavior.
    #[test]
    fn layering_ignores_edges_that_are_not_refinement_fields() {
        let input = PassInput {
            entities: vec![
                entity("a", "behavior"),
                entity("b", "behavior"),
                entity("t", "type"),
            ],
            edges: vec![
                edge("a", "b", "RefinesTo"),
                edge("a", "b", "RefinementChainLink"),
                edge("t", "a", REFINES_FIELD),
            ],
            ..Default::default()
        };
        assert!(pass_layering_verify(&input).is_empty());
    }

    fn behavior(id: &str, ensures: &str, is_abstract: bool) -> PassEntity {
        let mut e = entity(id, "behavior");
        if !ensures.is_empty() {
            e.fields.insert("ensures".to_string(), ensures.to_string());
        }
        if is_abstract {
            e.fields
                .insert(ABSTRACT_FLAG_FIELD.to_string(), "true".to_string());
        }
        e
    }

    #[test]
    fn refines_field_is_checked_like_a_refinement_entity() {
        let input = PassInput {
            entities: vec![
                behavior("spec", "a, b", true),
                behavior("keeps", "a, b, c", false),
                behavior("drops", "a", false),
            ],
            edges: vec![
                edge("keeps", "spec", REFINES_FIELD),
                edge("drops", "spec", REFINES_FIELD),
            ],
            ..Default::default()
        };
        let findings = pass_layering_verify(&input);
        assert_eq!(codes(&findings), vec!["E031"], "{findings:?}");
        assert!(
            findings[0].message.contains("'drops' refines 'spec'")
                && findings[0].message.contains("[b]"),
            "{}",
            findings[0].message
        );
    }

    #[test]
    fn entity_and_field_declaring_one_pair_report_once_via_the_entity() {
        let mut entities = vec![behavior("spec", "a, b", true), behavior("impl", "a", false)];
        entities.push(entity("r", "refinement"));
        let mut edges = refinement("r", "impl", "spec").to_vec();
        edges.push(edge("impl", "spec", REFINES_FIELD));
        let findings = pass_layering_verify(&PassInput {
            entities,
            edges,
            ..Default::default()
        });
        assert_eq!(codes(&findings), vec!["E031"], "{findings:?}");
        assert!(
            findings[0].message.starts_with("refinement 'r'"),
            "{}",
            findings[0].message
        );
    }

    #[test]
    fn refines_on_a_non_abstract_behavior_is_w110_but_entities_are_exempt() {
        let field = PassInput {
            entities: vec![behavior("base", "", false), behavior("derived", "", false)],
            edges: vec![edge("derived", "base", REFINES_FIELD)],
            ..Default::default()
        };
        let findings = pass_layering_verify(&field);
        assert_eq!(codes(&findings), vec!["W110"], "{findings:?}");
        assert!(matches!(findings[0].severity, PassSeverity::Warning));

        let entity_based = PassInput {
            entities: vec![
                behavior("base", "", false),
                behavior("derived", "", false),
                entity("r", "refinement"),
            ],
            edges: refinement("r", "derived", "base").to_vec(),
            ..Default::default()
        };
        assert!(pass_layering_verify(&entity_based).is_empty());
    }

    #[test]
    fn abstract_behavior_without_a_refinement_is_w030() {
        let lonely = PassInput {
            entities: vec![behavior("spec", "a", true)],
            edges: vec![],
            ..Default::default()
        };
        let findings = pass_layering_verify(&lonely);
        assert_eq!(codes(&findings), vec!["W030"], "{findings:?}");
        assert!(findings[0].message.contains("'spec'"));

        for edges in [
            vec![edge("impl", "spec", REFINES_FIELD)],
            refinement("r", "impl", "spec").to_vec(),
        ] {
            let input = PassInput {
                entities: vec![
                    behavior("spec", "a", true),
                    behavior("impl", "a", false),
                    entity("r", "refinement"),
                ],
                edges,
                ..Default::default()
            };
            assert!(
                pass_layering_verify(&input).is_empty(),
                "refined either way -> complete"
            );
        }
    }

    #[test]
    fn event_graph_flags_only_unconsumed_producers() {
        let input = PassInput {
            entities: vec![
                entity("tick", "event"),
                entity("done", "event"),
                entity("ticker", "behavior"),
                entity("finisher", "behavior"),
            ],
            edges: vec![
                edge("ticker", "tick", "produces"),
                edge("finisher", "done", "produces"),
                edge("handler", "done", "consumes"),
            ],
            ..Default::default()
        };
        let findings = pass_event_graph_analyze(&input);
        assert_eq!(codes(&findings), vec!["W029"]);
        assert!(findings[0].message.contains("tick"));
        assert!(
            !findings[0].message.contains("done"),
            "consumed event spared"
        );
    }
}

#[cfg(test)]
mod coverage_tracking_tests {
    use super::*;
    use specforge_extension_sdk::PassSeverity;

    fn entity(id: &str, kind: &str, testable: bool, tests: bool) -> PassEntity {
        let mut fields = std::collections::BTreeMap::new();
        if tests {
            fields.insert("tests".to_string(), "tests/x.rs".to_string());
        }
        PassEntity {
            id: id.to_string(),
            kind: kind.to_string(),
            fields,
            incoming_edge_count: 0,
            outgoing_edge_count: 0,
            span: None,
            testable,
            ..Default::default()
        }
    }

    #[test]
    fn coverage_tracking_aggregates_undischarged_items() {
        let input = PassInput {
            entities: vec![
                entity("inv1", "invariant", false, false),
                entity("feat1", "feature", true, true),
                entity("t1", "type", false, false),
            ],
            edges: vec![],
            ..Default::default()
        };
        let findings = pass_coverage_tracking(&input);
        assert_eq!(findings.len(), 1, "one aggregated W035");
        assert!(matches!(findings[0].severity, PassSeverity::Warning));
        assert!(
            findings[0].message.contains("inv1"),
            "{:?}",
            findings[0].message
        );
        assert!(
            !findings[0].message.contains("feat1"),
            "linked item is discharged: {:?}",
            findings[0].message
        );
        assert!(
            !findings[0].message.contains("t1"),
            "non-testable kinds are not coverage items: {:?}",
            findings[0].message
        );
    }

    #[test]
    fn coverage_tracking_silent_when_all_linked() {
        let input = PassInput {
            entities: vec![entity("inv1", "invariant", false, true)],
            edges: vec![],
            ..Default::default()
        };
        assert!(pass_coverage_tracking(&input).is_empty());
    }
}

fn dispatch(export: &str, input: &[u8]) -> Option<Result<Vec<u8>, String>> {
    match export {
        "__pass_condition_check" => Some(specforge_dispatch_pass_condition_check(input)),
        "__pass_layering_verify" => Some(specforge_dispatch_pass_layering_verify(input)),
        "__pass_event_graph_analyze" => Some(specforge_dispatch_pass_event_graph_analyze(input)),
        "__pass_coverage_tracking" => Some(specforge_dispatch_pass_coverage_tracking(input)),
        _ => None,
    }
}

specforge_extension_sdk::component_guest!(build = specforge_extension_build, handler = dispatch);

// -- C10-00/C10-11: process semantics + detector soundness slivers --

#[cfg(test)]
mod process_tests {
    use super::*;
    use specforge_extension_sdk::PassEdge;

    fn codes(findings: &[PassDiagnostic]) -> Vec<&str> {
        findings.iter().map(|f| f.code.as_str()).collect()
    }

    fn entity(id: &str, kind: &str) -> PassEntity {
        PassEntity {
            id: id.to_string(),
            kind: kind.to_string(),
            fields: std::collections::BTreeMap::new(),
            incoming_edge_count: 0,
            outgoing_edge_count: 0,
            span: None,
            testable: false,
            ..Default::default()
        }
    }

    fn edge(source: &str, target: &str, label: &str) -> PassEdge {
        PassEdge {
            source: source.to_string(),
            target: target.to_string(),
            label: label.to_string(),
        }
    }

    #[test]
    fn process_composition_cycle_is_e042() {
        let input = PassInput {
            entities: vec![
                entity("p1", "process"),
                entity("p2", "process"),
                entity("p3", "process"),
            ],
            edges: vec![
                edge("p1", "p2", "ProcessComposesProcess"),
                edge("p2", "p3", "ProcessComposesProcess"),
                edge("p3", "p1", "ProcessComposesProcess"),
            ],
            ..Default::default()
        };
        let findings = pass_event_graph_analyze(&input);
        assert_eq!(codes(&findings), vec!["E042"]);
        assert!(findings[0].message.contains("p1 -> p2 -> p3"));
    }

    #[test]
    fn acyclic_process_composition_is_clean() {
        let input = PassInput {
            entities: vec![entity("p1", "process"), entity("p2", "process")],
            edges: vec![edge("p1", "p2", "ProcessComposesProcess")],
            ..Default::default()
        };
        let findings = pass_event_graph_analyze(&input);
        assert!(findings.is_empty(), "acyclic composition: {findings:?}");
    }

    #[test]
    fn participation_counts_as_usage_for_w029() {
        // event produced by a behavior AND participating in a process: the
        // participation is usage, so W029 must not fire.
        let input = PassInput {
            entities: vec![
                entity("evt", "event"),
                entity("proc", "process"),
                entity("b", "behavior"),
            ],
            edges: vec![
                edge("b", "evt", "produces"),
                edge("evt", "proc", "EventParticipatesInProcess"),
            ],
            ..Default::default()
        };
        let findings = pass_event_graph_analyze(&input);
        assert!(
            !findings.iter().any(|f| f.code == "W029"),
            "participation counts as usage: {findings:?}"
        );
    }

    #[test]
    fn field_labeled_composition_edges_are_interpreted() {
        // The host labels process edges with the field name (sub_processes).
        let input = PassInput {
            entities: vec![entity("monitor", "process"), entity("scheduler", "process")],
            edges: vec![
                edge("monitor", "scheduler", "sub_processes"),
                edge("scheduler", "monitor", "sub_processes"),
            ],
            ..Default::default()
        };
        let findings = pass_event_graph_analyze(&input);
        assert_eq!(codes(&findings), vec!["E042"]);
    }

    #[test]
    fn self_cycle_in_process_composition_is_e042() {
        let input = PassInput {
            entities: vec![entity("p", "process")],
            edges: vec![edge("p", "p", "ProcessComposesProcess")],
            ..Default::default()
        };
        let findings = pass_event_graph_analyze(&input);
        assert_eq!(codes(&findings), vec!["E042"]);
    }

    #[test]
    fn layering_parallel_edges_report_once() {
        // two refinements naming the same b -> a pair: E041 must not dup.
        let mut entities = vec![entity("a", "behavior"), entity("b", "behavior")];
        let mut edges = Vec::new();
        for (r, concrete, abstract_id) in [("r1", "a", "b"), ("r2", "b", "a"), ("r3", "b", "a")] {
            entities.push(entity(r, "refinement"));
            edges.push(edge(r, concrete, REFINEMENT_CONCRETE_FIELD));
            edges.push(edge(r, abstract_id, REFINEMENT_ABSTRACT_FIELD));
        }
        let input = PassInput {
            entities,
            edges,
            ..Default::default()
        };
        let findings = pass_layering_verify(&input);
        let e041 = findings.iter().filter(|f| f.code == "E041").count();
        assert_eq!(e041, 1, "parallel edges yield one cycle diagnostic");
    }
}
