//! @specforge/formal — the formal-methods builtin, now authored with the
//! SpecForge extension SDK (SDK adoption; spec/extension-sdk docs).
//!
//! The describe payloads are the protocol envelopes extracted from the
//! in-process builtin (`crates/specforge-emitter/src/builtins/formal.rs`,
//! regenerated by `xtask extract-extension-json`). They are served through
//! the SDK's `raw_category` escape hatch, and the handshake is derived by the
//! SDK from the extension metadata — contribution flags included.

use specforge_extension_sdk::prelude::*;
use specforge_extension_sdk::{PassDiagnostic, PassEntity};

static DESCRIBE_ENTITIES: &[u8] = include_bytes!("describe_entities.json");
static DESCRIBE_EDGES: &[u8] = include_bytes!("describe_edges.json");
static DESCRIBE_FIELDS: &[u8] = include_bytes!("describe_fields.json");
static DESCRIBE_SHARED_FIELDS: &[u8] = include_bytes!("describe_shared_fields.json");
static DESCRIBE_ENHANCEMENTS: &[u8] = include_bytes!("describe_enhancements.json");
static DESCRIBE_VALIDATION_RULES: &[u8] = include_bytes!("describe_validation_rules.json");
static DESCRIBE_SURFACES: &[u8] = include_bytes!("describe_surfaces.json");
static DESCRIBE_FEATURE_FLAGS: &[u8] = include_bytes!("describe_feature_flags.json");

#[specforge_extension_sdk::extension(
    name = "@specforge/formal",
    version = "1.0.0",
)]
struct Formal;

impl Contributions for Formal {
    fn contribute(c: &mut ContributionsBuilder) {
        c.meta.peer_dependencies.push(PeerDependency {
            name: "@specforge/software".to_string(),
            version: "^1.0".to_string(),
            optional: false,
        });

        c.pass("condition_check", |p| {
            p.after("resolve");
        });

        for (category, bytes) in [
            ("entities", DESCRIBE_ENTITIES),
            ("edges", DESCRIBE_EDGES),
            ("fields", DESCRIBE_FIELDS),
            ("shared_fields", DESCRIBE_SHARED_FIELDS),
            ("enhancements", DESCRIBE_ENHANCEMENTS),
            ("validation_rules", DESCRIBE_VALIDATION_RULES),
            ("surfaces", DESCRIBE_SURFACES),
            ("feature_flags", DESCRIBE_FEATURE_FLAGS),
        ] {
            let envelope: serde_json::Value = serde_json::from_slice(bytes).unwrap_or_else(|e| {
                panic!("formal describe '{category}' is not valid JSON: {e}")
            });
            c.raw_category(category, envelope["items"].clone());
        }
    }
}

// ── Extension-owned compiler passes ────────────────────────────────────────
// Wire ABI (v1): `__pass_<name>` receives { "entities": [...] } (the host's
// ValidationEntity shape) and returns an array of host Diagnostic objects.
// The SDK's #[compiler_pass] attribute generates the export.

/// condition_check (Meyer's Design by Contract, RES-25 part I): a behavior
/// that obligates its callers (requires) must provide a benefit (ensures).
#[specforge_extension_sdk::compiler_pass(name = "condition_check", after = "resolve")]
fn pass_condition_check(entities: &[PassEntity]) -> Vec<PassDiagnostic> {
    let mut findings = Vec::new();
    for entity in entities {
        if entity.kind != "behavior" {
            continue;
        }
        let has_requires = non_empty(entity, "requires");
        let has_ensures = non_empty(entity, "ensures");
        if has_requires && !has_ensures {
            findings.push(
                PassDiagnostic::warning(
                    "W096",
                    format!("behavior '{}' declares requires but no ensures", entity.id),
                )
                .with_suggestion(
                    "add an ensures clause: a caller's obligation must buy a guarantee",
                ),
            );
        }
    }
    findings
}

fn non_empty(entity: &PassEntity, field: &str) -> bool {
    entity
        .fields
        .get(field)
        .is_some_and(|v| !v.trim().is_empty())
}
