use crate::checksum::prepend_checksum;
use crate::generator::{GenerateContext, GenerateResult};
use crate::slugify;
use specforge_common::{EntityKind, FieldValue, Scenario, VerifyKind, VerifyStatement};
use specforge_emitter::GeneratedFile;

/// Generate Rust test stub files for all testable entities with verify or scenario declarations.
pub fn generate_rust_test_stubs(ctx: &GenerateContext) -> GenerateResult {
    let mut files = Vec::new();
    let mut module_names = Vec::new();

    for file in ctx.files {
        for entity in &file.entities {
            if !entity.kind.is_testable() {
                continue;
            }
            let raw_id = entity.id.raw();

            let verify_stmts = match entity.fields.get("verify") {
                Some(FieldValue::VerifyList(v)) => Some(v),
                _ => None,
            };
            let scenarios = match entity.fields.get("scenario") {
                Some(FieldValue::ScenarioList(s)) => Some(s),
                _ => None,
            };

            if verify_stmts.is_none() && scenarios.is_none() {
                continue;
            }

            // Split verify stmts into test vs bench
            let (test_stmts, bench_stmts): (Vec<_>, Vec<_>) =
                verify_stmts.map(|v| v.as_slice()).unwrap_or_default()
                    .iter()
                    .partition(|v| v.kind != VerifyKind::Load);

            // Generate test file
            let content = generate_rust_stub_file(
                raw_id,
                entity.kind.clone(),
                &test_stmts,
                scenarios.map(|s| s.as_slice()),
            );
            let file_name = format!("tests/specforge/{raw_id}.rs");
            files.push(GeneratedFile {
                path: file_name,
                content: prepend_checksum(&content),
            });
            module_names.push(raw_id.to_string());

            // Generate bench file for load verifies
            if !bench_stmts.is_empty() {
                let bench_content = generate_bench_stub_file(raw_id, &bench_stmts);
                let bench_file = format!("benches/specforge/{raw_id}.rs");
                files.push(GeneratedFile {
                    path: bench_file,
                    content: prepend_checksum(&bench_content),
                });
            }
        }
    }

    // Generate module tree entry point
    if !module_names.is_empty() {
        module_names.sort();
        let mod_lines: Vec<String> = module_names
            .iter()
            .map(|name| format!("mod {name};"))
            .collect();
        let mod_content = format!(
            "// Generated by specforge — DO NOT EDIT\n{}\n",
            mod_lines.join("\n")
        );
        files.push(GeneratedFile {
            path: "tests/specforge/mod.rs".to_string(),
            content: prepend_checksum(&mod_content),
        });
        // Entry point that includes the module tree
        let entry_content =
            "// Generated by specforge — DO NOT EDIT\nmod specforge;\n".to_string();
        files.push(GeneratedFile {
            path: "tests/specforge_tests.rs".to_string(),
            content: prepend_checksum(&entry_content),
        });
    }

    GenerateResult {
        files,
        warnings: Vec::new(),
        errors: Vec::new(),
        entity_checksums: std::collections::HashMap::new(),
    }
}

fn generate_rust_stub_file(
    entity_id: &str,
    entity_kind: EntityKind,
    verify: &[&VerifyStatement],
    scenarios: Option<&[Scenario]>,
) -> String {
    let mut lines = Vec::new();
    lines.push("// Generated by specforge — DO NOT EDIT".to_string());
    lines.push(format!(
        "// Entity: {entity_id} ({kind})",
        kind = entity_kind.keyword()
    ));
    lines.push(String::new());

    for stmt in verify {
        let slug = slugify::slugify(&stmt.description);
        let fn_name = format!("{entity_id}__{slug}");
        let kind = stmt.kind.as_str();
        lines.push("#[test]".to_string());
        lines.push(format!("fn {fn_name}() {{"));
        lines.push(format!(
            "    // {kind}: {}",
            stmt.description
        ));
        lines.push(format!("    todo!(\"implement {kind} test\")"));
        lines.push("}".to_string());
        lines.push(String::new());
    }

    if let Some(scenario_list) = scenarios {
        for scenario in scenario_list {
            let slug = slugify::slugify(&scenario.title);
            let fn_name = format!("{entity_id}__{slug}");
            lines.push("#[test]".to_string());
            lines.push(format!("fn {fn_name}() {{"));
            for step in &scenario.steps {
                let step_kind = match step.kind {
                    specforge_common::ScenarioStepKind::Given => "given",
                    specforge_common::ScenarioStepKind::When => "when",
                    specforge_common::ScenarioStepKind::Then => "then",
                };
                lines.push(format!("    // {step_kind}: {}", step.description));
            }
            lines.push("    todo!(\"implement scenario test\")".to_string());
            lines.push("}".to_string());
            lines.push(String::new());
        }
    }

    lines.join("\n")
}

fn generate_bench_stub_file(entity_id: &str, stmts: &[&VerifyStatement]) -> String {
    let mut lines = Vec::new();
    lines.push("// Generated by specforge — DO NOT EDIT".to_string());
    lines.push(format!("// Entity: {entity_id} (benchmark)"));
    lines.push("use criterion::{criterion_group, criterion_main, Criterion};".to_string());
    lines.push(String::new());

    for stmt in stmts {
        let slug = slugify::slugify(&stmt.description);
        let fn_name = format!("bench_{entity_id}__{slug}");
        lines.push(format!("fn {fn_name}(c: &mut Criterion) {{"));
        lines.push(format!(
            "    c.bench_function(\"{entity_id}: {}\", |b| {{",
            stmt.description
        ));
        lines.push("        b.iter(|| {".to_string());
        lines.push("            todo!(\"implement load test\")".to_string());
        lines.push("        });".to_string());
        lines.push("    });".to_string());
        lines.push("}".to_string());
        lines.push(String::new());
    }

    let bench_fns: Vec<String> = stmts
        .iter()
        .map(|s| format!("bench_{entity_id}__{}", slugify::slugify(&s.description)))
        .collect();
    lines.push(format!(
        "criterion_group!(benches, {});",
        bench_fns.join(", ")
    ));
    lines.push("criterion_main!(benches);".to_string());
    lines.push(String::new());

    lines.join("\n")
}

/// Check if a file body still contains `todo!("implement` markers.
/// If the body was modified by a user (no todo markers), return true to skip regeneration.
pub fn has_user_modifications(content: &str) -> bool {
    // If checksum doesn't verify, user may have modified the file
    if !crate::checksum::verify_checksum(content) {
        // Check if any todo markers remain
        return !content.contains("todo!(\"implement");
    }
    false
}

#[cfg(test)]
mod tests {
    use super::*;
    use specforge_common::{ScenarioStep, ScenarioStepKind, SourceSpan, VerifyKind};

    #[test]
    fn rust_stub_from_verify() {
        let stmts = vec![
            VerifyStatement {
                kind: VerifyKind::Unit,
                description: "rejects empty email".to_string(),
            },
            VerifyStatement {
                kind: VerifyKind::Unit,
                description: "accepts valid email".to_string(),
            },
        ];
        let refs: Vec<&VerifyStatement> = stmts.iter().collect();
        let content = generate_rust_stub_file("validate_input", EntityKind::Behavior, &refs, None);
        assert!(content.contains("#[test]"), "got:\n{content}");
        assert!(
            content.contains("fn validate_input__rejects_empty_email()"),
            "got:\n{content}"
        );
        assert!(
            content.contains("fn validate_input__accepts_valid_email()"),
            "got:\n{content}"
        );
        assert!(
            content.contains("todo!(\"implement unit test\")"),
            "got:\n{content}"
        );
    }

    #[test]
    fn rust_stub_from_scenario() {
        let span = SourceSpan::new("test.spec", 1, 1, 1, 1);
        let scenario = Scenario {
            title: "successful login".to_string(),
            steps: vec![
                ScenarioStep {
                    kind: ScenarioStepKind::Given,
                    description: "a registered user".to_string(),
                    span: span.clone(),
                },
                ScenarioStep {
                    kind: ScenarioStepKind::When,
                    description: "they enter credentials".to_string(),
                    span: span.clone(),
                },
                ScenarioStep {
                    kind: ScenarioStepKind::Then,
                    description: "they see the dashboard".to_string(),
                    span: span.clone(),
                },
            ],
            span,
        };
        let content = generate_rust_stub_file(
            "user_login",
            EntityKind::Capability,
            &[],
            Some(&[scenario]),
        );
        assert!(
            content.contains("fn user_login__successful_login()"),
            "got:\n{content}"
        );
        assert!(
            content.contains("// given: a registered user"),
            "got:\n{content}"
        );
        assert!(
            content.contains("// when: they enter credentials"),
            "got:\n{content}"
        );
        assert!(
            content.contains("// then: they see the dashboard"),
            "got:\n{content}"
        );
    }

    #[test]
    fn bench_stubs_generated() {
        let stmts = vec![VerifyStatement {
            kind: VerifyKind::Load,
            description: "handles 1000 requests".to_string(),
        }];
        let refs: Vec<&VerifyStatement> = stmts.iter().collect();
        let content = generate_bench_stub_file("api_endpoint", &refs);
        assert!(content.contains("use criterion::"), "got:\n{content}");
        assert!(
            content.contains("fn bench_api_endpoint__handles_1000_requests"),
            "got:\n{content}"
        );
        assert!(
            content.contains("criterion_group!"),
            "got:\n{content}"
        );
    }

    #[test]
    fn has_entity_comment() {
        let content = generate_rust_stub_file(
            "data_integrity",
            EntityKind::Invariant,
            &[&VerifyStatement {
                kind: VerifyKind::Property,
                description: "holds under mutation".to_string(),
            }],
            None,
        );
        assert!(content.contains("// Entity: data_integrity (invariant)"));
    }

    #[test]
    fn user_modifications_detected() {
        // Content with todo markers is not considered user-modified
        let with_todo = "// @specforge-checksum:sha256:abc\nfn test() { todo!(\"implement unit test\") }";
        assert!(!has_user_modifications(with_todo));

        // Content without todo markers and bad checksum is user-modified
        let without_todo = "// @specforge-checksum:sha256:abc\nfn test() { assert_eq!(1, 1) }";
        assert!(has_user_modifications(without_todo));
    }
}
