use std::collections::HashMap;

use crate::checksum::prepend_checksum;
use crate::generator::{self, GenerateContext, GenerateResult, Generator};
use crate::naming;
use specforge_common::{EntityKind, FieldMap, FieldValue, NamingStyle, ResultStyle};
use specforge_emitter::GeneratedFile;

pub struct RustGenerator;

impl Generator for RustGenerator {
    fn name(&self) -> &str {
        "rust"
    }

    fn generate(&self, ctx: &GenerateContext) -> GenerateResult {
        let mut files = Vec::new();
        let mut warnings = Vec::new();
        let mut entity_checksums = HashMap::new();

        let entity_fields = build_entity_fields(ctx);
        let use_serde = ctx.gen_config.extra.get("serde").is_some_and(|v| v == "true");
        let use_async = ctx.gen_config.extra.get("async").is_some_and(|v| v == "true");
        let result_style = &ctx.gen_config.result_style;

        // Generate types
        let type_nodes = ctx.graph.nodes_of_kind(EntityKind::TypeDef);
        let mut module_names: Vec<String> = Vec::new();
        for node in &type_nodes {
            let raw_id = node.id.raw();
            if let Some(fields) = entity_fields.get(raw_id) {
                entity_checksums.insert(
                    raw_id.to_string(),
                    generator::compute_entity_checksum(fields),
                );
                let (content, _type_name) = generate_type(raw_id, fields, use_serde, result_style);
                let file_stem = naming::transform(raw_id, NamingStyle::SnakeCase);
                let file_name = format!("{file_stem}.rs");
                module_names.push(file_stem);
                files.push(GeneratedFile {
                    path: file_name,
                    content: prepend_checksum(&content),
                });
            }
        }

        // Generate ports
        let port_nodes = ctx.graph.nodes_of_kind(EntityKind::Port);
        for node in &port_nodes {
            let raw_id = node.id.raw();
            if let Some(fields) = entity_fields.get(raw_id) {
                entity_checksums.insert(
                    raw_id.to_string(),
                    generator::compute_entity_checksum(fields),
                );
                let (content, _trait_name) =
                    generate_port(raw_id, fields, use_async, use_serde, result_style);
                let file_stem = naming::transform(raw_id, NamingStyle::SnakeCase);
                let file_name = format!("{file_stem}.rs");
                module_names.push(file_stem);
                files.push(GeneratedFile {
                    path: file_name,
                    content: prepend_checksum(&content),
                });
            }
        }

        // Generate test stubs if tests adapter is configured
        if ctx.gen_config.tests.is_some() {
            let stub_result = crate::rust_test_stubs::generate_rust_test_stubs(ctx);
            files.extend(stub_result.files);
            warnings.extend(stub_result.warnings);
        }

        // Generate mod.rs barrel file
        module_names.sort();
        if !module_names.is_empty() {
            let mod_lines: Vec<String> = module_names
                .iter()
                .map(|name| format!("pub mod {name};"))
                .collect();
            let mod_content = format!(
                "// Generated by specforge — DO NOT EDIT\n{}\n",
                mod_lines.join("\n")
            );
            files.push(GeneratedFile {
                path: "mod.rs".to_string(),
                content: prepend_checksum(&mod_content),
            });
        }

        GenerateResult {
            files,
            warnings,
            errors: Vec::new(),
            entity_checksums,
        }
    }
}

/// Map entity raw IDs to their AST field maps for fast lookup.
fn build_entity_fields<'a>(ctx: &'a GenerateContext) -> HashMap<&'a str, &'a FieldMap> {
    let mut map = HashMap::new();
    for file in ctx.files {
        for entity in &file.entities {
            map.insert(entity.id.raw(), &entity.fields);
        }
    }
    map
}

/// Generate a Rust type definition from a spec type entity.
/// Returns (file_content, exported_name).
fn generate_type(
    name: &str,
    fields: &FieldMap,
    use_serde: bool,
    result_style: &ResultStyle,
) -> (String, String) {
    let rust_name = naming::transform(name, NamingStyle::PascalCase);

    // Union type (has `variants` field)
    if let Some(FieldValue::StringList(variants)) = fields.get("variants") {
        let serde_derive = if use_serde {
            ", Serialize, Deserialize"
        } else {
            ""
        };
        let variant_lines: Vec<String> = variants
            .iter()
            .map(|v| {
                let pascal = naming::transform(v, NamingStyle::PascalCase);
                format!("    {pascal},")
            })
            .collect();
        let content = format!(
            "// Generated by specforge — DO NOT EDIT\n\
             // Entity: {name} (type)\n\
             \n\
             #[derive(Debug, Clone, PartialEq{serde_derive})]\n\
             pub enum {rust_name} {{\n\
             {variants}\n\
             }}\n",
            variants = variant_lines.join("\n"),
        );
        return (content, rust_name);
    }

    // Struct type (has `fields` field)
    if let Some(FieldValue::Block(struct_fields)) = fields.get("fields") {
        let serde_derive = if use_serde {
            ", Serialize, Deserialize"
        } else {
            ""
        };
        let mut lines = Vec::new();
        for (field_name, field_value) in struct_fields.iter() {
            if let FieldValue::Block(entry) = field_value {
                let annotations = match entry.get("annotations") {
                    Some(FieldValue::StringList(anns)) => anns.clone(),
                    _ => Vec::new(),
                };

                let is_optional = annotations.iter().any(|a| a == "@optional");
                let is_readonly = annotations.iter().any(|a| a == "@readonly");
                let is_unique = annotations.iter().any(|a| a == "@unique");

                let type_str = match entry.get("type") {
                    Some(FieldValue::String(t)) => map_type_expr(t, result_style),
                    _ => "()".to_string(),
                };

                let final_type = if is_optional {
                    format!("Option<{type_str}>")
                } else {
                    type_str
                };

                let rust_field_name = naming::transform(field_name, NamingStyle::SnakeCase);

                let mut doc_comments = Vec::new();
                if is_readonly {
                    doc_comments.push("    /// @readonly".to_string());
                }
                if is_unique {
                    doc_comments.push("    /// @unique".to_string());
                }
                for comment in &doc_comments {
                    lines.push(comment.clone());
                }
                lines.push(format!("    pub {rust_field_name}: {final_type},"));
            }
        }

        let content = format!(
            "// Generated by specforge — DO NOT EDIT\n\
             // Entity: {name} (type)\n\
             \n\
             #[derive(Debug, Clone{serde_derive})]\n\
             pub struct {rust_name} {{\n\
             {fields}\n\
             }}\n",
            fields = lines.join("\n"),
        );
        return (content, rust_name);
    }

    // Fallback: empty struct
    let content = format!(
        "// Generated by specforge — DO NOT EDIT\n\
         // Entity: {name} (type)\n\
         \n\
         #[derive(Debug, Clone)]\n\
         pub struct {rust_name} {{}}\n",
    );
    (content, rust_name)
}

/// Generate a Rust trait from a spec port entity.
/// Returns (file_content, exported_name).
fn generate_port(
    name: &str,
    fields: &FieldMap,
    use_async: bool,
    _use_serde: bool,
    result_style: &ResultStyle,
) -> (String, String) {
    let rust_name = naming::transform(name, NamingStyle::PascalCase);

    let direction = match fields.get("direction") {
        Some(FieldValue::Enum(d)) => d.as_str(),
        _ => "inbound",
    };

    let mut methods = Vec::new();
    for (key, value) in fields.iter() {
        if let Some(method_name) = key.strip_prefix("method:") {
            if let FieldValue::String(signature) = value {
                let method = parse_method_signature(method_name, signature, use_async, result_style);
                methods.push(method);
            }
        }
    }

    let async_trait_attr = if use_async {
        "#[async_trait::async_trait]\n"
    } else {
        ""
    };

    let content = format!(
        "// Generated by specforge — DO NOT EDIT\n\
         // Entity: {name} (port, {direction})\n\
         \n\
         {async_trait_attr}\
         pub trait {rust_name} {{\n\
         {methods}\n\
         }}\n",
        methods = methods.join("\n"),
    );
    (content, rust_name)
}

/// Parse a method signature string into a Rust trait method.
fn parse_method_signature(
    method_name: &str,
    signature: &str,
    use_async: bool,
    result_style: &ResultStyle,
) -> String {
    let params_and_rest = signature.find('(').and_then(|start| {
        signature.find(')').map(|end| {
            let params = &signature[start + 1..end];
            let rest = &signature[end + 1..];
            (params.trim(), rest.trim())
        })
    });

    let (params_str, return_type) = match params_and_rest {
        Some((params, rest)) => {
            let ret = rest.strip_prefix("->").map(|r| r.trim()).unwrap_or("void");
            (params, ret)
        }
        None => ("", "void"),
    };

    let rust_method_name = naming::transform(method_name, NamingStyle::SnakeCase);
    let async_prefix = if use_async { "async " } else { "" };

    let rust_params = if params_str.is_empty() {
        "&self".to_string()
    } else {
        let params: Vec<String> = params_str
            .split(',')
            .map(|p| {
                let p = p.trim();
                if let Some((name, type_expr)) = p.split_once(':') {
                    let rust_name = naming::transform(name.trim(), NamingStyle::SnakeCase);
                    let rust_type = map_type_expr(type_expr.trim(), result_style);
                    format!("{rust_name}: {rust_type}")
                } else {
                    p.to_string()
                }
            })
            .collect();
        format!("&self, {}", params.join(", "))
    };

    let rust_return = map_type_expr(return_type, result_style);
    if rust_return == "()" {
        format!("    {async_prefix}fn {rust_method_name}({rust_params});")
    } else {
        format!("    {async_prefix}fn {rust_method_name}({rust_params}) -> {rust_return};")
    }
}

/// Map a spec type expression to a Rust type.
fn map_type_expr(expr: &str, result_style: &ResultStyle) -> String {
    let expr = expr.trim();
    match expr {
        "string" => "String".to_string(),
        "integer" | "int" => "i64".to_string(),
        "float" | "number" => "f64".to_string(),
        "bool" | "boolean" => "bool".to_string(),
        "void" => "()".to_string(),
        "never" => "!".to_string(),
        _ => {
            // Optional: `Type?`
            if let Some(inner) = expr.strip_suffix('?') {
                let mapped = map_type_expr(inner, result_style);
                return format!("Option<{mapped}>");
            }

            // Array: `Type[]`
            if let Some(inner) = expr.strip_suffix("[]") {
                let mapped = map_type_expr(inner, result_style);
                return format!("Vec<{mapped}>");
            }

            // Result<T, E>
            if let Some(inner) = expr.strip_prefix("Result<").and_then(|s| s.strip_suffix('>')) {
                if let Some((ok_type, err_type)) = inner.split_once(',') {
                    let ok = map_type_expr(ok_type.trim(), result_style);
                    let err = map_type_expr(err_type.trim(), result_style);
                    return match result_style {
                        ResultStyle::Plain => format!("Result<{ok}, {err}>"),
                        ResultStyle::HexDi => format!("Result<{ok}, {err}>"),
                        ResultStyle::Never => ok,
                        ResultStyle::Custom(path) => format!("{path}<{ok}, {err}>"),
                    };
                }
            }

            // Named type — use as-is (assumed PascalCase)
            expr.to_string()
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn map_primitives() {
        let rs = ResultStyle::Plain;
        assert_eq!(map_type_expr("string", &rs), "String");
        assert_eq!(map_type_expr("integer", &rs), "i64");
        assert_eq!(map_type_expr("int", &rs), "i64");
        assert_eq!(map_type_expr("float", &rs), "f64");
        assert_eq!(map_type_expr("number", &rs), "f64");
        assert_eq!(map_type_expr("bool", &rs), "bool");
        assert_eq!(map_type_expr("boolean", &rs), "bool");
        assert_eq!(map_type_expr("void", &rs), "()");
        assert_eq!(map_type_expr("never", &rs), "!");
    }

    #[test]
    fn map_optional() {
        let rs = ResultStyle::Plain;
        assert_eq!(map_type_expr("string?", &rs), "Option<String>");
        assert_eq!(map_type_expr("User?", &rs), "Option<User>");
    }

    #[test]
    fn map_array() {
        let rs = ResultStyle::Plain;
        assert_eq!(map_type_expr("string[]", &rs), "Vec<String>");
        assert_eq!(map_type_expr("User[]", &rs), "Vec<User>");
    }

    #[test]
    fn map_result() {
        assert_eq!(
            map_type_expr("Result<User, Error>", &ResultStyle::Plain),
            "Result<User, Error>"
        );
    }

    #[test]
    fn map_result_never() {
        assert_eq!(
            map_type_expr("Result<User, Error>", &ResultStyle::Never),
            "User"
        );
    }

    #[test]
    fn map_named_type() {
        let rs = ResultStyle::Plain;
        assert_eq!(map_type_expr("UserProfile", &rs), "UserProfile");
    }

    #[test]
    fn generate_struct_type_basic() {
        let mut struct_fields = FieldMap::new();
        let mut name_entry = FieldMap::new();
        name_entry.insert("type", FieldValue::String("string".to_string()));
        struct_fields.insert("name", FieldValue::Block(name_entry));

        let mut age_entry = FieldMap::new();
        age_entry.insert("type", FieldValue::String("integer".to_string()));
        age_entry.insert(
            "annotations",
            FieldValue::StringList(vec!["@optional".to_string()]),
        );
        struct_fields.insert("age", FieldValue::Block(age_entry));

        let mut fields = FieldMap::new();
        fields.insert("fields", FieldValue::Block(struct_fields));

        let (content, type_name) = generate_type("User", &fields, false, &ResultStyle::Plain);
        assert_eq!(type_name, "User");
        assert!(content.contains("pub struct User {"), "got:\n{content}");
        assert!(content.contains("pub name: String,"), "got:\n{content}");
        assert!(
            content.contains("pub age: Option<i64>,"),
            "got:\n{content}"
        );
        assert!(
            content.contains("#[derive(Debug, Clone)]"),
            "got:\n{content}"
        );
    }

    #[test]
    fn generate_struct_with_serde() {
        let mut struct_fields = FieldMap::new();
        let mut name_entry = FieldMap::new();
        name_entry.insert("type", FieldValue::String("string".to_string()));
        struct_fields.insert("name", FieldValue::Block(name_entry));

        let mut fields = FieldMap::new();
        fields.insert("fields", FieldValue::Block(struct_fields));

        let (content, _) = generate_type("User", &fields, true, &ResultStyle::Plain);
        assert!(
            content.contains("#[derive(Debug, Clone, Serialize, Deserialize)]"),
            "got:\n{content}"
        );
    }

    #[test]
    fn generate_union_type() {
        let mut fields = FieldMap::new();
        fields.insert(
            "variants",
            FieldValue::StringList(vec![
                "active".to_string(),
                "inactive".to_string(),
                "banned".to_string(),
            ]),
        );

        let (content, type_name) =
            generate_type("UserStatus", &fields, false, &ResultStyle::Plain);
        assert_eq!(type_name, "UserStatus");
        assert!(content.contains("pub enum UserStatus {"), "got:\n{content}");
        assert!(content.contains("    Active,"), "got:\n{content}");
        assert!(content.contains("    Inactive,"), "got:\n{content}");
        assert!(content.contains("    Banned,"), "got:\n{content}");
    }

    #[test]
    fn generate_port_trait() {
        let mut fields = FieldMap::new();
        fields.insert(
            "method:save",
            FieldValue::String("method save(user: User) -> Result<void, Error>".to_string()),
        );
        fields.insert(
            "method:findById",
            FieldValue::String("method findById(id: string) -> User?".to_string()),
        );

        let (content, trait_name) =
            generate_port("UserRepository", &fields, false, false, &ResultStyle::Plain);
        assert_eq!(trait_name, "UserRepository");
        assert!(
            content.contains("pub trait UserRepository {"),
            "got:\n{content}"
        );
        assert!(
            content.contains("fn save(&self, user: User) -> Result<(), Error>;"),
            "got:\n{content}"
        );
        assert!(
            content.contains("fn find_by_id(&self, id: String) -> Option<User>;"),
            "got:\n{content}"
        );
    }

    #[test]
    fn generate_async_port() {
        let mut fields = FieldMap::new();
        fields.insert(
            "method:list",
            FieldValue::String("method list() -> User[]".to_string()),
        );

        let (content, _) = generate_port("UserRepo", &fields, true, false, &ResultStyle::Plain);
        assert!(
            content.contains("async fn list(&self) -> Vec<User>;"),
            "got:\n{content}"
        );
        assert!(
            content.contains("#[async_trait::async_trait]"),
            "got:\n{content}"
        );
    }

    #[test]
    fn readonly_and_unique_annotations() {
        let mut struct_fields = FieldMap::new();
        let mut id_entry = FieldMap::new();
        id_entry.insert("type", FieldValue::String("string".to_string()));
        id_entry.insert(
            "annotations",
            FieldValue::StringList(vec!["@readonly".to_string()]),
        );
        struct_fields.insert("id", FieldValue::Block(id_entry));

        let mut email_entry = FieldMap::new();
        email_entry.insert("type", FieldValue::String("string".to_string()));
        email_entry.insert(
            "annotations",
            FieldValue::StringList(vec!["@unique".to_string()]),
        );
        struct_fields.insert("email", FieldValue::Block(email_entry));

        let mut fields = FieldMap::new();
        fields.insert("fields", FieldValue::Block(struct_fields));

        let (content, _) = generate_type("Entity", &fields, false, &ResultStyle::Plain);
        assert!(content.contains("/// @readonly"), "got:\n{content}");
        assert!(content.contains("/// @unique"), "got:\n{content}");
    }
}
