use crate::checksum::prepend_checksum;
use crate::generator::{GenerateContext, GenerateResult};
use specforge_common::{EntityKind, FieldValue, Scenario, VerifyStatement};
use specforge_emitter::GeneratedFile;

/// Generate test stub files for all testable entities that have verify or scenario declarations.
pub fn generate_test_stubs(ctx: &GenerateContext) -> GenerateResult {
    let mut files = Vec::new();

    for file in ctx.files {
        for entity in &file.entities {
            if !entity.kind.is_testable() {
                continue;
            }
            let raw_id = entity.id.raw();

            let verify_stmts = match entity.fields.get("verify") {
                Some(FieldValue::VerifyList(v)) => Some(v),
                _ => None,
            };
            let scenarios = match entity.fields.get("scenario") {
                Some(FieldValue::ScenarioList(s)) => Some(s),
                _ => None,
            };

            if verify_stmts.is_none() && scenarios.is_none() {
                continue;
            }

            let content = generate_stub_file(
                raw_id,
                entity.kind.clone(),
                verify_stmts.map(|v| v.as_slice()),
                scenarios.map(|s| s.as_slice()),
            );
            let file_name = format!("__tests__/{raw_id}.test.ts");
            files.push(GeneratedFile {
                path: file_name,
                content: prepend_checksum(&content),
            });
        }
    }

    GenerateResult {
        files,
        warnings: Vec::new(),
        errors: Vec::new(),
        entity_checksums: std::collections::HashMap::new(),
    }
}

fn generate_stub_file(
    entity_id: &str,
    entity_kind: EntityKind,
    verify: Option<&[VerifyStatement]>,
    scenarios: Option<&[Scenario]>,
) -> String {
    let mut lines = Vec::new();
    lines.push("// Generated by specforge — DO NOT EDIT".to_string());
    lines.push(format!("// Entity: {entity_id} ({kind})", kind = entity_kind.keyword()));
    lines.push("import { describe, it, expect } from 'vitest';".to_string());
    lines.push(String::new());
    lines.push(format!("describe('{entity_id}', () => {{"));

    if let Some(stmts) = verify {
        for stmt in stmts {
            let desc = &stmt.description;
            let kind = stmt.kind.as_str();
            lines.push(format!("  it('{desc}', () => {{"));
            lines.push(format!("    // TODO: implement {kind} test"));
            lines.push("    expect(true).toBe(false);".to_string());
            lines.push("  });".to_string());
            lines.push(String::new());
        }
    }

    if let Some(scenario_list) = scenarios {
        for scenario in scenario_list {
            let title = &scenario.title;
            lines.push(format!("  describe('{title}', () => {{"));
            for step in &scenario.steps {
                let step_kind = match step.kind {
                    specforge_common::ScenarioStepKind::Given => "given",
                    specforge_common::ScenarioStepKind::When => "when",
                    specforge_common::ScenarioStepKind::Then => "then",
                };
                let desc = &step.description;
                lines.push(format!("    it('{step_kind}: {desc}', () => {{"));
                lines.push("      // TODO: implement".to_string());
                lines.push("      expect(true).toBe(false);".to_string());
                lines.push("    });".to_string());
                lines.push(String::new());
            }
            lines.push("  });".to_string());
            lines.push(String::new());
        }
    }

    lines.push("});".to_string());
    lines.push(String::new());
    lines.join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use specforge_common::{ScenarioStep, ScenarioStepKind, SourceSpan, VerifyKind};

    #[test]
    fn stub_from_verify() {
        let content = generate_stub_file(
            "validate_input",
            EntityKind::Behavior,
            Some(&[
                VerifyStatement {
                    kind: VerifyKind::Unit,
                    description: "rejects empty email".to_string(),
                },
                VerifyStatement {
                    kind: VerifyKind::Unit,
                    description: "accepts valid email".to_string(),
                },
            ]),
            None,
        );
        assert!(content.contains("describe('validate_input'"));
        assert!(content.contains("it('rejects empty email'"));
        assert!(content.contains("it('accepts valid email'"));
        assert!(content.contains("// TODO: implement unit test"));
    }

    #[test]
    fn stub_from_scenario() {
        let span = SourceSpan::new("test.spec", 1, 1, 1, 1);
        let content = generate_stub_file(
            "user_login",
            EntityKind::Capability,
            None,
            Some(&[Scenario {
                title: "successful login".to_string(),
                steps: vec![
                    ScenarioStep {
                        kind: ScenarioStepKind::Given,
                        description: "a registered user".to_string(),
                        span: span.clone(),
                    },
                    ScenarioStep {
                        kind: ScenarioStepKind::When,
                        description: "they enter credentials".to_string(),
                        span: span.clone(),
                    },
                    ScenarioStep {
                        kind: ScenarioStepKind::Then,
                        description: "they see the dashboard".to_string(),
                        span: span.clone(),
                    },
                ],
                span,
            }]),
        );
        assert!(content.contains("describe('user_login'"));
        assert!(content.contains("describe('successful login'"));
        assert!(content.contains("given: a registered user"));
        assert!(content.contains("when: they enter credentials"));
        assert!(content.contains("then: they see the dashboard"));
    }

    #[test]
    fn stub_has_entity_comment() {
        let content = generate_stub_file(
            "data_integrity",
            EntityKind::Invariant,
            Some(&[VerifyStatement {
                kind: VerifyKind::Property,
                description: "holds under mutation".to_string(),
            }]),
            None,
        );
        assert!(content.contains("// Entity: data_integrity (invariant)"));
    }
}
