use std::collections::HashMap;

use crate::checksum::prepend_checksum;
use crate::generator::{self, GenerateContext, GenerateResult, Generator};
use crate::naming;
use specforge_common::{EntityKind, FieldMap, FieldValue, NamingStyle, ResultStyle};
use specforge_emitter::GeneratedFile;

pub struct TypeScriptGenerator;

impl Generator for TypeScriptGenerator {
    fn name(&self) -> &str {
        "typescript"
    }

    fn generate(&self, ctx: &GenerateContext) -> GenerateResult {
        let mut files = Vec::new();
        let mut warnings = Vec::new();
        let mut entity_checksums = HashMap::new();
        let naming_style = ctx.gen_config.naming;

        // Build entity_fields map: entity_id -> &FieldMap
        let entity_fields = build_entity_fields(ctx);

        // Generate types
        let type_nodes = ctx.graph.nodes_of_kind(EntityKind::TypeDef);
        let mut type_names: Vec<String> = Vec::new();
        for node in &type_nodes {
            let raw_id = node.id.raw();
            if let Some(fields) = entity_fields.get(raw_id) {
                entity_checksums.insert(
                    raw_id.to_string(),
                    generator::compute_entity_checksum(fields),
                );
                let (content, name) =
                    generate_type(raw_id, fields, ctx.gen_config.readonly, &ctx.gen_config.result_style, naming_style);
                let file_name = format!("{}.ts", naming::to_file_name(raw_id));
                type_names.push(name);
                files.push(GeneratedFile {
                    path: file_name,
                    content: prepend_checksum(&content),
                });
            }
        }

        // Generate ports
        let port_nodes = ctx.graph.nodes_of_kind(EntityKind::Port);
        let mut port_names: Vec<String> = Vec::new();
        for node in &port_nodes {
            let raw_id = node.id.raw();
            if let Some(fields) = entity_fields.get(raw_id) {
                entity_checksums.insert(
                    raw_id.to_string(),
                    generator::compute_entity_checksum(fields),
                );
                let (content, name) = generate_port(raw_id, fields, &ctx.gen_config.result_style, naming_style);
                let file_name = format!("{}.ts", naming::to_file_name(raw_id));
                port_names.push(name);
                files.push(GeneratedFile {
                    path: file_name,
                    content: prepend_checksum(&content),
                });
            }
        }

        // Generate test stubs if tests adapter is configured
        if ctx.gen_config.tests.is_some() {
            let stub_result = crate::test_stubs::generate_test_stubs(ctx);
            files.extend(stub_result.files);
            warnings.extend(stub_result.warnings);
        }

        // Generate index barrel file
        let mut all_exports: Vec<String> = Vec::new();
        for node in &type_nodes {
            let file_stem = naming::to_file_name(node.id.raw());
            all_exports.push(format!("export * from './{file_stem}';"));
        }
        for node in &port_nodes {
            let file_stem = naming::to_file_name(node.id.raw());
            all_exports.push(format!("export * from './{file_stem}';"));
        }
        all_exports.sort();

        if !all_exports.is_empty() {
            let index_content = format!(
                "// Generated by specforge — DO NOT EDIT\n{}\n",
                all_exports.join("\n")
            );
            files.push(GeneratedFile {
                path: "index.ts".to_string(),
                content: prepend_checksum(&index_content),
            });
        }

        GenerateResult {
            files,
            warnings,
            errors: Vec::new(),
            entity_checksums,
        }
    }
}

/// Map entity raw IDs to their AST field maps for fast lookup.
fn build_entity_fields<'a>(ctx: &'a GenerateContext) -> std::collections::HashMap<&'a str, &'a FieldMap> {
    let mut map = std::collections::HashMap::new();
    for file in ctx.files {
        for entity in &file.entities {
            map.insert(entity.id.raw(), &entity.fields);
        }
    }
    map
}

/// Generate a TypeScript type definition from a spec type entity.
/// Returns (file_content, exported_name).
fn generate_type(
    name: &str,
    fields: &FieldMap,
    readonly: bool,
    result_style: &ResultStyle,
    naming_style: NamingStyle,
) -> (String, String) {
    let ts_name = name.to_string(); // Already PascalCase from spec convention

    // Check for union type (has `variants` field)
    if let Some(FieldValue::StringList(variants)) = fields.get("variants") {
        let variant_strs: Vec<String> = variants.iter().map(|v| format!("'{v}'")).collect();
        let content = format!(
            "// Generated by specforge — DO NOT EDIT\n\
             // Entity: {name} (type)\n\
             \n\
             export type {ts_name} = {variants};\n",
            variants = variant_strs.join(" | "),
        );
        return (content, ts_name);
    }

    // Struct type (has `fields` field)
    if let Some(FieldValue::Block(struct_fields)) = fields.get("fields") {
        let mut lines = Vec::new();
        for (field_name, field_value) in struct_fields.iter() {
            if let FieldValue::Block(entry) = field_value {
                let annotations = match entry.get("annotations") {
                    Some(FieldValue::StringList(anns)) => anns.clone(),
                    _ => Vec::new(),
                };

                let is_literal = annotations.iter().any(|a| a == "@literal");
                let is_optional = annotations.iter().any(|a| a == "@optional");
                let is_unique = annotations.iter().any(|a| a == "@unique");

                // @literal fields are always readonly; otherwise respect the global flag
                let is_readonly = is_literal
                    || (readonly && annotations.iter().any(|a| a == "@readonly"));

                let type_str = if is_literal {
                    // Use the raw type value as a literal string type.
                    // The AST stores it as a quoted string: `"ParseError"` → strip outer quotes.
                    match entry.get("type") {
                        Some(FieldValue::String(t)) => {
                            let stripped = t.trim_matches('"');
                            format!("\"{stripped}\"")
                        }
                        _ => "unknown".to_string(),
                    }
                } else {
                    match entry.get("type") {
                        Some(FieldValue::String(t)) => map_type_expr(t, result_style),
                        _ => "unknown".to_string(),
                    }
                };

                // Preserve leading underscore (e.g., `_tag` → `_tag` not `tag`)
                let (prefix, base) = if let Some(rest) = field_name.strip_prefix('_') {
                    ("_", rest)
                } else {
                    ("", field_name)
                };
                let ts_field_name = format!("{prefix}{}", naming::transform(base, naming_style));
                let readonly_prefix = if is_readonly { "readonly " } else { "" };
                let optional_suffix = if is_optional { "?" } else { "" };

                let mut line = format!("  {readonly_prefix}{ts_field_name}{optional_suffix}: {type_str};");
                if is_unique {
                    line.push_str(" // @unique");
                }
                lines.push(line);
            }
        }

        let content = format!(
            "// Generated by specforge — DO NOT EDIT\n\
             // Entity: {name} (type)\n\
             \n\
             export interface {ts_name} {{\n\
             {fields}\n\
             }}\n",
            fields = lines.join("\n"),
        );
        return (content, ts_name);
    }

    // Fallback: empty interface
    let content = format!(
        "// Generated by specforge — DO NOT EDIT\n\
         // Entity: {name} (type)\n\
         \n\
         export interface {ts_name} {{}}\n",
    );
    (content, ts_name)
}

/// Generate a TypeScript port interface from a spec port entity.
/// Returns (file_content, exported_name).
fn generate_port(
    name: &str,
    fields: &FieldMap,
    result_style: &ResultStyle,
    naming_style: NamingStyle,
) -> (String, String) {
    let ts_name = name.to_string(); // Already PascalCase

    // Read direction field (default "inbound" if absent)
    let direction = match fields.get("direction") {
        Some(FieldValue::Enum(d)) => d.as_str(),
        _ => "inbound",
    };

    let mut methods = Vec::new();
    for (key, value) in fields.iter() {
        if let Some(method_name) = key.strip_prefix("method:") {
            if let FieldValue::String(signature) = value {
                let ts_method =
                    parse_method_signature(method_name, signature, result_style, naming_style);
                methods.push(ts_method);
            }
        }
    }

    let content = format!(
        "// Generated by specforge — DO NOT EDIT\n\
         // Entity: {name} (port, {direction})\n\
         \n\
         /** @direction {direction} */\n\
         export interface {ts_name} {{\n\
         {methods}\n\
         }}\n",
        methods = methods.join("\n"),
    );
    (content, ts_name)
}

/// Parse a method signature string like `method save(data: UserData) -> Result<void, Error>`
/// into a TypeScript method signature.
fn parse_method_signature(
    method_name: &str,
    signature: &str,
    result_style: &ResultStyle,
    naming_style: NamingStyle,
) -> String {
    // The signature text is: `method <name>(<params>) -> <return_type>`
    // Extract params and return type
    let params_and_rest = signature
        .find('(')
        .and_then(|start| {
            signature.find(')').map(|end| {
                let params = &signature[start + 1..end];
                let rest = &signature[end + 1..];
                (params.trim(), rest.trim())
            })
        });

    let (params_str, return_type) = match params_and_rest {
        Some((params, rest)) => {
            let ret = rest
                .strip_prefix("->")
                .map(|r| r.trim())
                .unwrap_or("void");
            (params, ret)
        }
        None => ("", "void"),
    };

    let ts_method_name = naming::transform(method_name, naming_style);

    // Convert params
    let ts_params = if params_str.is_empty() {
        String::new()
    } else {
        params_str
            .split(',')
            .map(|p| {
                let p = p.trim();
                if let Some((name, type_expr)) = p.split_once(':') {
                    let ts_param_name = naming::transform(name.trim(), naming_style);
                    format!("{ts_param_name}: {}", map_type_expr(type_expr.trim(), result_style))
                } else {
                    p.to_string()
                }
            })
            .collect::<Vec<_>>()
            .join(", ")
    };

    let ts_return = map_type_expr(return_type, result_style);
    format!("  {ts_method_name}({ts_params}): {ts_return};")
}

/// Map a spec type expression to a TypeScript type.
fn map_type_expr(expr: &str, result_style: &ResultStyle) -> String {
    let expr = expr.trim();
    match expr {
        "string" => "string".to_string(),
        "integer" | "int" => "number".to_string(),
        "float" | "number" => "number".to_string(),
        "bool" | "boolean" => "boolean".to_string(),
        "void" => "void".to_string(),
        "never" => "never".to_string(),
        _ => {
            // Optional: `Type?`
            if let Some(inner) = expr.strip_suffix('?') {
                let mapped = map_type_expr(inner, result_style);
                return format!("{mapped} | undefined");
            }

            // Array: `Type[]`
            if let Some(inner) = expr.strip_suffix("[]") {
                let mapped = map_type_expr(inner, result_style);
                return format!("{mapped}[]");
            }

            // Result<T, E>
            if let Some(inner) = expr.strip_prefix("Result<").and_then(|s| s.strip_suffix('>')) {
                if let Some((ok_type, err_type)) = inner.split_once(',') {
                    let ok = map_type_expr(ok_type.trim(), result_style);
                    let err = map_type_expr(err_type.trim(), result_style);
                    return match result_style {
                        ResultStyle::Plain => format!("{{ ok: {ok} }} | {{ err: {err} }}"),
                        ResultStyle::HexDi => format!("Result<{ok}, {err}>"),
                        ResultStyle::Never => ok,
                        ResultStyle::Custom(path) => format!("{path}<{ok}, {err}>"),
                    };
                }
            }

            // Named type — use as-is (PascalCase identifier)
            expr.to_string()
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn map_primitives() {
        let rs = ResultStyle::Plain;
        assert_eq!(map_type_expr("string", &rs), "string");
        assert_eq!(map_type_expr("integer", &rs), "number");
        assert_eq!(map_type_expr("bool", &rs), "boolean");
        assert_eq!(map_type_expr("void", &rs), "void");
        assert_eq!(map_type_expr("never", &rs), "never");
    }

    #[test]
    fn map_optional() {
        let rs = ResultStyle::Plain;
        assert_eq!(map_type_expr("string?", &rs), "string | undefined");
    }

    #[test]
    fn map_array() {
        let rs = ResultStyle::Plain;
        assert_eq!(map_type_expr("string[]", &rs), "string[]");
        assert_eq!(map_type_expr("User[]", &rs), "User[]");
    }

    #[test]
    fn map_result_plain() {
        assert_eq!(
            map_type_expr("Result<User, Error>", &ResultStyle::Plain),
            "{ ok: User } | { err: Error }"
        );
    }

    #[test]
    fn map_result_hex_di() {
        assert_eq!(
            map_type_expr("Result<User, Error>", &ResultStyle::HexDi),
            "Result<User, Error>"
        );
    }

    #[test]
    fn map_result_never() {
        assert_eq!(
            map_type_expr("Result<User, Error>", &ResultStyle::Never),
            "User"
        );
    }

    #[test]
    fn map_named_type() {
        let rs = ResultStyle::Plain;
        assert_eq!(map_type_expr("UserProfile", &rs), "UserProfile");
    }

    #[test]
    fn parse_method_basic() {
        let result = parse_method_signature(
            "save",
            "method save(data: UserData) -> Result<void, Error>",
            &ResultStyle::Plain,
            NamingStyle::CamelCase,
        );
        assert_eq!(result, "  save(data: UserData): { ok: void } | { err: Error };");
    }

    #[test]
    fn parse_method_no_params() {
        let result = parse_method_signature(
            "list",
            "method list() -> User[]",
            &ResultStyle::Plain,
            NamingStyle::CamelCase,
        );
        assert_eq!(result, "  list(): User[];");
    }

    #[test]
    fn generate_struct_type() {
        let mut struct_fields = FieldMap::new();
        let mut name_entry = FieldMap::new();
        name_entry.insert("type", FieldValue::String("string".to_string()));
        struct_fields.insert("name", FieldValue::Block(name_entry));

        let mut age_entry = FieldMap::new();
        age_entry.insert("type", FieldValue::String("integer".to_string()));
        age_entry.insert("annotations", FieldValue::StringList(vec!["@optional".to_string()]));
        struct_fields.insert("age", FieldValue::Block(age_entry));

        let mut fields = FieldMap::new();
        fields.insert("fields", FieldValue::Block(struct_fields));

        let (content, name) = generate_type("User", &fields, false, &ResultStyle::Plain, NamingStyle::CamelCase);
        assert_eq!(name, "User");
        assert!(content.contains("export interface User {"));
        assert!(content.contains("  name: string;"));
        assert!(content.contains("  age?: number;"));
    }

    #[test]
    fn generate_union_type() {
        let mut fields = FieldMap::new();
        fields.insert(
            "variants",
            FieldValue::StringList(vec![
                "active".to_string(),
                "inactive".to_string(),
                "banned".to_string(),
            ]),
        );

        let (content, name) = generate_type("UserStatus", &fields, false, &ResultStyle::Plain, NamingStyle::CamelCase);
        assert_eq!(name, "UserStatus");
        assert!(content.contains("export type UserStatus = 'active' | 'inactive' | 'banned';"));
    }

    #[test]
    fn generate_port_interface() {
        let mut fields = FieldMap::new();
        fields.insert(
            "method:save",
            FieldValue::String("method save(user: User) -> Result<void, Error>".to_string()),
        );
        fields.insert(
            "method:findById",
            FieldValue::String("method findById(id: string) -> User?".to_string()),
        );

        let (content, name) = generate_port("UserRepository", &fields, &ResultStyle::Plain, NamingStyle::CamelCase);
        assert_eq!(name, "UserRepository");
        assert!(content.contains("export interface UserRepository {"));
        assert!(content.contains("save(user: User): { ok: void } | { err: Error };"));
        assert!(content.contains("findById(id: string): User | undefined;"));
    }

    #[test]
    fn readonly_annotation() {
        let mut struct_fields = FieldMap::new();
        let mut id_entry = FieldMap::new();
        id_entry.insert("type", FieldValue::String("string".to_string()));
        id_entry.insert("annotations", FieldValue::StringList(vec!["@readonly".to_string()]));
        struct_fields.insert("id", FieldValue::Block(id_entry));

        let mut fields = FieldMap::new();
        fields.insert("fields", FieldValue::Block(struct_fields));

        let (content, _) = generate_type("Entity", &fields, true, &ResultStyle::Plain, NamingStyle::CamelCase);
        assert!(content.contains("readonly id: string;"));
    }

    #[test]
    fn unique_annotation() {
        let mut struct_fields = FieldMap::new();
        let mut email_entry = FieldMap::new();
        email_entry.insert("type", FieldValue::String("string".to_string()));
        email_entry.insert("annotations", FieldValue::StringList(vec!["@unique".to_string()]));
        struct_fields.insert("email", FieldValue::Block(email_entry));

        let mut fields = FieldMap::new();
        fields.insert("fields", FieldValue::Block(struct_fields));

        let (content, _) = generate_type("User", &fields, false, &ResultStyle::Plain, NamingStyle::CamelCase);
        assert!(content.contains("email: string; // @unique"));
    }

    // Gap 1: @literal annotation produces discriminated union tag
    #[test]
    fn error_type_discriminated_union() {
        let mut struct_fields = FieldMap::new();

        let mut tag_entry = FieldMap::new();
        tag_entry.insert("type", FieldValue::String("\"ParseError\"".to_string()));
        tag_entry.insert("annotations", FieldValue::StringList(vec!["@literal".to_string()]));
        struct_fields.insert("_tag", FieldValue::Block(tag_entry));

        let mut msg_entry = FieldMap::new();
        msg_entry.insert("type", FieldValue::String("string".to_string()));
        struct_fields.insert("message", FieldValue::Block(msg_entry));

        let mut span_entry = FieldMap::new();
        span_entry.insert("type", FieldValue::String("SourceSpan".to_string()));
        struct_fields.insert("span", FieldValue::Block(span_entry));

        let mut expected_entry = FieldMap::new();
        expected_entry.insert("type", FieldValue::String("string".to_string()));
        expected_entry.insert("annotations", FieldValue::StringList(vec!["@optional".to_string()]));
        struct_fields.insert("expected", FieldValue::Block(expected_entry));

        let mut fields = FieldMap::new();
        fields.insert("fields", FieldValue::Block(struct_fields));

        let (content, _) = generate_type("ParseError", &fields, false, &ResultStyle::Plain, NamingStyle::CamelCase);
        assert!(content.contains("readonly _tag: \"ParseError\";"), "got:\n{content}");
        assert!(content.contains("  message: string;"));
        assert!(content.contains("  span: SourceSpan;"));
        assert!(content.contains("  expected?: string;"));
    }

    // Gap 2: port direction distinguished
    #[test]
    fn port_direction_distinguished() {
        let mut fields = FieldMap::new();
        fields.insert("direction", FieldValue::Enum("outbound".to_string()));
        fields.insert(
            "method:write",
            FieldValue::String("method write(data: string) -> void".to_string()),
        );

        let (content, _) = generate_port("FileSystem", &fields, &ResultStyle::Plain, NamingStyle::CamelCase);
        assert!(content.contains("(port, outbound)"), "got:\n{content}");
        assert!(content.contains("/** @direction outbound */"), "got:\n{content}");
    }

    #[test]
    fn port_direction_defaults_inbound() {
        let mut fields = FieldMap::new();
        fields.insert(
            "method:parse",
            FieldValue::String("method parse(input: string) -> void".to_string()),
        );

        let (content, _) = generate_port("CompilerApi", &fields, &ResultStyle::Plain, NamingStyle::CamelCase);
        assert!(content.contains("(port, inbound)"), "got:\n{content}");
        assert!(content.contains("/** @direction inbound */"), "got:\n{content}");
    }

    // Gap 4: naming convention applied to fields
    #[test]
    fn naming_camelcase_fields() {
        let mut struct_fields = FieldMap::new();
        let mut entry = FieldMap::new();
        entry.insert("type", FieldValue::String("string".to_string()));
        struct_fields.insert("user_name", FieldValue::Block(entry));

        let mut fields = FieldMap::new();
        fields.insert("fields", FieldValue::Block(struct_fields));

        let (content, _) = generate_type("User", &fields, false, &ResultStyle::Plain, NamingStyle::CamelCase);
        assert!(content.contains("userName: string;"), "got:\n{content}");
    }

    #[test]
    fn naming_snake_case_methods() {
        let mut fields = FieldMap::new();
        fields.insert(
            "method:findById",
            FieldValue::String("method findById(userId: string) -> User?".to_string()),
        );

        let (content, _) = generate_port("UserRepo", &fields, &ResultStyle::Plain, NamingStyle::SnakeCase);
        assert!(content.contains("find_by_id("), "got:\n{content}");
        assert!(content.contains("user_id: "), "got:\n{content}");
    }
}
